//! `CrabRule` → RFC 5228 Sieve emitter.
//!
//! Renders a set of [`CrabRule`]s into a *personal* Sieve script — the kind a
//! client installs over `ManageSieve` (`PUTSCRIPT` + `SETACTIVE`). This is **not**
//! a byte-clone of the server's global `categories.sieve` (`sieve_before`):
//! Dovecot evaluates `sieve_before`, then the personal active script, then
//! `sieve_after`, so the two coexist. The emitter therefore only has to produce
//! valid, semantically-correct Sieve that Dovecot's `sievec` accepts — not output
//! identical to the server's emitter.
//!
//! SECURITY: emits only header / `Subject` / `From`-domain tests and
//! `fileinto` / `setflag` actions. The [`MatchExpr`] AST has no body / full-address
//! variant, so this module structurally cannot emit a body-touching test.
//!
//! Validation oracle: Dovecot's `sievec` (see `tests/sievec_validation.rs`) — the
//! "compiler is the arbiter" check for this module, mirroring how the server
//! validates `categories.sieve`.

use crate::crab_rule::{Action, CrabRule, MatchExpr};

/// Render a slice of rules into a single Sieve script.
///
/// Rules are emitted highest-`score`-first (higher wins; a firing rule with
/// `stop_on_match` short-circuits the rest via `stop;`). A rule whose condition
/// is statically unsatisfiable is emitted as a skipped comment rather than as
/// invalid Sieve, and an always-true condition emits its actions unconditionally.
///
/// BUG ASSUMPTION: the required-extension set is derived purely from the actions
/// present; if a new [`Action`] variant needs a Sieve extension, extend
/// [`required_extensions`] on the same change.
#[must_use]
pub fn to_sieve(rules: &[CrabRule]) -> String {
    // Stable sort by score DESC so equal-score rules keep input order.
    let mut ordered: Vec<&CrabRule> = rules.iter().collect();
    ordered.sort_by_key(|r| core::cmp::Reverse(r.score));

    let mut out = String::new();
    out.push_str("# Generated by ThunderCrab (thundercrab-core::sieve). Do not hand-edit.\n");
    out.push_str("# Personal active script; layers on top of the server's global sieve_before.\n\n");

    let reqs = required_extensions(&ordered);
    if !reqs.is_empty() {
        out.push_str("require ");
        out.push_str(&string_list(&reqs));
        out.push_str(";\n\n");
    }

    for r in &ordered {
        emit_rule(&mut out, r);
    }
    out
}

/// Tri-state rendering of a match expression, so `allof`/`anyof`/`not` can fold
/// statically-constant sub-expressions instead of emitting invalid Sieve (there
/// is no `true`/`false` literal test in RFC 5228).
enum TestRepr {
    AlwaysTrue,
    AlwaysFalse,
    Test(String),
}

fn emit_rule(out: &mut String, r: &CrabRule) {
    out.push_str("# ");
    out.push_str(&r.id);
    out.push_str(": ");
    out.push_str(&one_line(&r.display_name));
    out.push('\n');

    match render_test(&r.when) {
        TestRepr::AlwaysFalse => {
            out.push_str("# (skipped: condition is never satisfiable)\n\n");
        }
        TestRepr::AlwaysTrue => {
            for line in action_lines(&r.action) {
                out.push_str(&line);
                out.push('\n');
            }
            if r.stop_on_match {
                out.push_str("stop;\n");
            }
            out.push('\n');
        }
        TestRepr::Test(test) => {
            out.push_str("if ");
            out.push_str(&test);
            out.push_str(" {\n");
            for line in action_lines(&r.action) {
                out.push_str("    ");
                out.push_str(&line);
                out.push('\n');
            }
            if r.stop_on_match {
                out.push_str("    stop;\n");
            }
            out.push_str("}\n\n");
        }
    }
}

fn render_test(e: &MatchExpr) -> TestRepr {
    match e {
        MatchExpr::Always => TestRepr::AlwaysTrue,
        MatchExpr::HeaderContains { header, substring } => {
            TestRepr::Test(format!("header :contains {} {}", quote(header), quote(substring)))
        }
        MatchExpr::HasHeader { header } => TestRepr::Test(format!("exists {}", quote(header))),
        MatchExpr::FromDomainIn { domains } => {
            // Leading `@` is stripped: Sieve's `address :domain` yields the bare
            // domain (e.g. "github.com"), matched exactly with `:is`.
            let stripped: Vec<String> =
                domains.iter().map(|d| d.trim_start_matches('@').to_string()).collect();
            if stripped.iter().all(String::is_empty) {
                return TestRepr::AlwaysFalse;
            }
            TestRepr::Test(format!("address :domain :is \"from\" {}", string_list(&stripped)))
        }
        MatchExpr::SubjectContainsAny { needles } => {
            if needles.is_empty() {
                return TestRepr::AlwaysFalse;
            }
            TestRepr::Test(format!("header :contains \"subject\" {}", string_list(needles)))
        }
        MatchExpr::Not { expr } => match render_test(expr) {
            TestRepr::AlwaysTrue => TestRepr::AlwaysFalse,
            TestRepr::AlwaysFalse => TestRepr::AlwaysTrue,
            TestRepr::Test(t) => TestRepr::Test(format!("not {t}")),
        },
        MatchExpr::All { exprs } => combine(exprs, true),
        MatchExpr::Any { exprs } => combine(exprs, false),
    }
}

/// Fold a list of sub-expressions into `allof(..)` / `anyof(..)`, short-circuiting
/// on constants: an always-true member is dropped from `allof` (and makes `anyof`
/// true); an always-false member is dropped from `anyof` (and makes `allof` false).
fn combine(exprs: &[MatchExpr], all: bool) -> TestRepr {
    let mut tests: Vec<String> = Vec::new();
    for e in exprs {
        match render_test(e) {
            TestRepr::AlwaysTrue => {
                if !all {
                    return TestRepr::AlwaysTrue; // anyof(.., true, ..) == true
                }
            }
            TestRepr::AlwaysFalse => {
                if all {
                    return TestRepr::AlwaysFalse; // allof(.., false, ..) == false
                }
            }
            TestRepr::Test(t) => tests.push(t),
        }
    }
    match tests.len() {
        0 => {
            if all {
                TestRepr::AlwaysTrue // allof() of nothing == true
            } else {
                TestRepr::AlwaysFalse // anyof() of nothing == false
            }
        }
        1 => TestRepr::Test(tests.pop().unwrap_or_default()),
        _ => {
            let kw = if all { "allof" } else { "anyof" };
            TestRepr::Test(format!("{kw}({})", tests.join(", ")))
        }
    }
}

fn action_lines(a: &Action) -> Vec<String> {
    match a {
        Action::FileInto { folder } => vec![format!("fileinto :create {};", quote(folder))],
        Action::SetFlag { flag } => vec![format!("setflag {};", quote(flag))],
        Action::Sequence { actions } => actions.iter().flat_map(action_lines).collect(),
    }
}

fn required_extensions(rules: &[&CrabRule]) -> Vec<String> {
    let mut fileinto = false;
    let mut flags = false;
    for r in rules {
        scan_action(&r.action, &mut fileinto, &mut flags);
    }
    let mut v = Vec::new();
    if fileinto {
        v.push("fileinto".to_string());
        v.push("mailbox".to_string()); // for `fileinto :create`
    }
    if flags {
        v.push("imap4flags".to_string());
    }
    v
}

fn scan_action(a: &Action, fileinto: &mut bool, flags: &mut bool) {
    match a {
        Action::FileInto { .. } => *fileinto = true,
        Action::SetFlag { .. } => *flags = true,
        Action::Sequence { actions } => {
            for x in actions {
                scan_action(x, fileinto, flags);
            }
        }
    }
}

/// Quote + escape a string for a Sieve double-quoted literal (RFC 5228 §2.4.2:
/// only `\` and `"` are special inside quoted strings).
fn quote(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 2);
    o.push('"');
    for c in s.chars() {
        match c {
            '\\' => o.push_str("\\\\"),
            '"' => o.push_str("\\\""),
            _ => o.push(c),
        }
    }
    o.push('"');
    o
}

fn string_list(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| quote(s)).collect();
    format!("[{}]", inner.join(", "))
}

/// Collapse a display name to a single comment-safe line.
fn one_line(s: &str) -> String {
    s.replace(['\n', '\r'], " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crab_rule::{Action, CrabRule, MatchExpr, RuleOrigin};

    fn rule(id: &str, when: MatchExpr, action: Action) -> CrabRule {
        CrabRule {
            id: id.to_string(),
            display_name: id.to_string(),
            when,
            action,
            score: 50,
            stop_on_match: true,
            origin: RuleOrigin::User,
        }
    }

    #[test]
    fn empty_rules_emit_header_only() {
        let s = to_sieve(&[]);
        assert!(s.contains("# Generated by ThunderCrab"));
        assert!(!s.contains("require")); // no actions -> no extensions
    }

    #[test]
    fn from_domain_emits_address_domain_is() {
        let r = rule(
            "gh",
            MatchExpr::FromDomainIn { domains: vec!["@github.com".into()] },
            Action::FileInto { folder: "Dev".into() },
        );
        let s = to_sieve(&[r]);
        assert!(s.contains("require [\"fileinto\", \"mailbox\"];"), "{s}");
        assert!(s.contains("address :domain :is \"from\" [\"github.com\"]"), "{s}");
        assert!(s.contains("fileinto :create \"Dev\";"), "{s}");
        assert!(s.contains("stop;"), "{s}");
    }

    #[test]
    fn subject_any_and_header_contains() {
        let r = rule(
            "promo",
            MatchExpr::SubjectContainsAny { needles: vec!["sale".into(), "% off".into()] },
            Action::FileInto { folder: "Promotions".into() },
        );
        let s = to_sieve(&[r]);
        assert!(s.contains("header :contains \"subject\" [\"sale\", \"% off\"]"), "{s}");
    }

    #[test]
    fn allof_anyof_not_fold() {
        let r = rule(
            "combo",
            MatchExpr::All {
                exprs: vec![
                    MatchExpr::HasHeader { header: "List-Id".into() },
                    MatchExpr::Not {
                        expr: Box::new(MatchExpr::HeaderContains {
                            header: "X-Priority".into(),
                            substring: "1".into(),
                        }),
                    },
                ],
            },
            Action::FileInto { folder: "Lists".into() },
        );
        let s = to_sieve(&[r]);
        assert!(s.contains("allof(exists \"List-Id\", not header :contains \"X-Priority\" \"1\")"), "{s}");
    }

    #[test]
    fn always_is_unconditional_no_if() {
        let r = rule("catchall", MatchExpr::Always, Action::FileInto { folder: "Archive".into() });
        let s = to_sieve(&[r]);
        // No `if` for an always-true rule; bare action.
        assert!(!s.contains("if "), "{s}");
        assert!(s.contains("fileinto :create \"Archive\";"), "{s}");
    }

    #[test]
    fn unsatisfiable_any_is_skipped() {
        let r = rule(
            "dead",
            MatchExpr::Any { exprs: vec![] }, // anyof() == false
            Action::FileInto { folder: "Nowhere".into() },
        );
        let s = to_sieve(&[r]);
        assert!(s.contains("skipped: condition is never satisfiable"), "{s}");
        // The require line may still mention fileinto; the rule's ACTION must not be emitted.
        assert!(!s.contains("fileinto :create"), "{s}");
    }

    #[test]
    fn higher_score_emitted_first() {
        let lo = CrabRule { score: 10, ..rule("lo", MatchExpr::HasHeader { header: "A".into() }, Action::FileInto { folder: "Lo".into() }) };
        let hi = CrabRule { score: 90, ..rule("hi", MatchExpr::HasHeader { header: "B".into() }, Action::FileInto { folder: "Hi".into() }) };
        let s = to_sieve(&[lo, hi]);
        assert!(s.find("# hi:").unwrap() < s.find("# lo:").unwrap(), "{s}");
    }

    #[test]
    fn setflag_pulls_imap4flags_and_escapes() {
        let r = rule(
            "flagit",
            MatchExpr::HasHeader { header: "X-VIP".into() },
            Action::SetFlag { flag: "\\Flagged".into() },
        );
        let s = to_sieve(&[r]);
        assert!(s.contains("\"imap4flags\""), "{s}");
        assert!(s.contains("setflag \"\\\\Flagged\";"), "{s}");
    }
}
