//! `thundercrab-ffi` — the UniFFI surface that native UIs (Android Compose
//! first, then a Linux desktop UI) call into. The Rust core stays the single
//! source of truth; this crate is a thin, logic-free pass-through.
//!
//! BUG ASSUMPTION: every function here is a trivial forwarder. If real logic
//! appears in this crate, that's the bug — it belongs in `thundercrab-core`.
//! SECURITY: nothing here touches message bodies (the core invariant). This
//! crate only exposes config + (later) header-level operations.
//!
//! Bindings are generated by `uniffi-bindgen` during the platform build
//! (Kotlin for Android, Swift for iOS). See docs/ROADMAP-ANDROID-FIRST.md.

uniffi::setup_scaffolding!();

/// Library version, surfaced to the UI's About screen.
#[uniffi::export]
pub fn thundercrab_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Connection settings a mail app needs. Returned to the platform UI so the
/// account-setup screen can be pre-filled instead of asking the user to know
/// ports and TLS modes.
#[derive(uniffi::Record, Clone, Debug)]
pub struct AccountSettings {
    pub host: String,
    pub imap_port: u16,
    pub imap_security: String,
    pub smtp_port: u16,
    /// Carrier-friendly fallback if the network blocks the primary SMTP port.
    pub smtp_fallback_port: u16,
    pub smtp_security: String,
    pub username: String,
}

/// Auto-config for a PlausiDen mailbox — mirrors the server's live submission
/// setup (IMAPS 993, submission 587/STARTTLS, 2525 fallback for carriers that
/// block 587). The UI passes only the address; everything else is derived.
#[uniffi::export]
pub fn plausiden_account(username: String) -> AccountSettings {
    AccountSettings {
        host: "mail.plausiden.com".to_string(),
        imap_port: 993,
        imap_security: "SSL/TLS".to_string(),
        smtp_port: 587,
        smtp_fallback_port: 2525,
        smtp_security: "STARTTLS".to_string(),
        username,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_is_nonempty() {
        assert!(!thundercrab_version().is_empty());
    }

    #[test]
    fn plausiden_autoconfig_matches_server() {
        let a = plausiden_account("kadyn@plausiden.com".into());
        assert_eq!(a.host, "mail.plausiden.com");
        assert_eq!(a.imap_port, 993);
        assert_eq!(a.smtp_port, 587);
        assert_eq!(a.smtp_fallback_port, 2525);
    }
}
