//! `thundercrab-ffi` — the UniFFI surface that native UIs (Android Compose
//! first, then a Linux desktop UI) call into. The Rust core stays the single
//! source of truth; this crate is a thin, logic-free pass-through.
//!
//! BUG ASSUMPTION: every function here is a trivial forwarder. If real logic
//! appears in this crate, that's the bug — it belongs in `thundercrab-core`,
//! `thundercrab-imap`, or `thundercrab-suggestions`. The *only* work this
//! layer is allowed to do is shape-translation at the FFI seam: bridging types
//! UniFFI cannot represent (tuples, fixed-size arrays, `DateTime`, the
//! `MatchExpr`/`Action` AST) to/from the canonical core types. No business
//! logic, no rule evaluation, no protocol decisions.
//!
//! SECURITY: nothing here touches message bodies (the core invariant). The
//! exposed surface is config + folder/header-level operations + the rule and
//! flag-event stores. `fetch_body` exists only as a `NotImplemented` stub —
//! reading bodies is gated on explicit ratification and a new IMAP method that
//! does not exist yet (see the stub's docs).
//!
//! Bindings are generated by `uniffi-bindgen` during the platform build
//! (Kotlin for Android, Swift for iOS). See docs/ROADMAP-ANDROID-FIRST.md.

use std::sync::Arc;

use chrono::{DateTime, TimeZone as _, Utc};
use thundercrab_core::{
    Action, CrabRule, Db, FlagEvent, FlagSource, MatchExpr, RuleOrigin, to_sieve,
};
use thundercrab_imap::rust_imap::RustImapBackend;
use thundercrab_imap::smtp::{self, OutboundMessage, SmtpEncryption};
use thundercrab_imap::{AccountConfig, Backend as _, BackendError, managesieve};
use thundercrab_suggestions::{apply_suggestion, derive_rule_candidates};
use tokio::sync::Mutex;

uniffi::setup_scaffolding!();

// =============================================================================
// Errors
// =============================================================================

/// Errors surfaced across the FFI boundary. Maps the backend / store / parse
/// failure space onto a flat, fielded enum that UniFFI renders as a Kotlin
/// sealed class. Each variant carries a human-readable detail string.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum FfiError {
    /// Network or TLS transport failure.
    #[error("transport: {detail}")]
    Transport {
        /// Human-readable detail.
        detail: String,
    },
    /// Authentication or authorization failure.
    #[error("auth: {detail}")]
    Auth {
        /// Human-readable detail.
        detail: String,
    },
    /// Server returned a protocol-level error, or a JSON/store error occurred.
    #[error("protocol: {detail}")]
    Protocol {
        /// Human-readable detail.
        detail: String,
    },
    /// The requested operation is not implemented in this build.
    #[error("not implemented: {detail}")]
    NotImplemented {
        /// Human-readable detail.
        detail: String,
    },
    /// A value handed across the FFI seam was malformed (bad JSON, wrong-length
    /// hash, unparseable address, etc.).
    #[error("invalid input: {detail}")]
    InvalidInput {
        /// Human-readable detail.
        detail: String,
    },
}

impl From<BackendError> for FfiError {
    fn from(e: BackendError) -> Self {
        match e {
            BackendError::Transport(m) => Self::Transport { detail: m },
            BackendError::Auth(m) => Self::Auth { detail: m },
            BackendError::Protocol(m) => Self::Protocol { detail: m },
            BackendError::NotImplemented(m) => Self::NotImplemented {
                detail: m.to_string(),
            },
        }
    }
}

impl From<thundercrab_core::DbError> for FfiError {
    fn from(e: thundercrab_core::DbError) -> Self {
        // The store's failure modes are all "the backing protocol said no";
        // they map onto Protocol so the UI's catch-all handles them.
        Self::Protocol {
            detail: e.to_string(),
        }
    }
}

impl From<thundercrab_suggestions::SafetyError> for FfiError {
    fn from(e: thundercrab_suggestions::SafetyError) -> Self {
        Self::InvalidInput {
            detail: e.to_string(),
        }
    }
}

// =============================================================================
// Version
// =============================================================================

/// Library version, surfaced to the UI's About screen.
#[uniffi::export]
#[must_use]
pub fn thundercrab_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// =============================================================================
// Account config
// =============================================================================

/// Connection settings a mail app needs, mirroring the canonical
/// [`thundercrab_imap::AccountConfig`] field-for-field. Returned to the
/// platform UI so the account-setup screen can be pre-filled instead of asking
/// the user to know ports.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiAccountConfig {
    /// Hostname for IMAP and `ManageSieve`.
    pub imap_host: String,
    /// IMAPS port.
    pub imap_port: u16,
    /// SMTP submission host.
    pub smtp_host: String,
    /// SMTP submission port.
    pub smtp_port: u16,
    /// `ManageSieve` port.
    pub sieve_port: u16,
    /// Username (full email address).
    pub username: String,
}

impl From<AccountConfig> for FfiAccountConfig {
    fn from(c: AccountConfig) -> Self {
        Self {
            imap_host: c.imap_host,
            imap_port: c.imap_port,
            smtp_host: c.smtp_host,
            smtp_port: c.smtp_port,
            sieve_port: c.sieve_port,
            username: c.username,
        }
    }
}

impl From<&FfiAccountConfig> for AccountConfig {
    fn from(c: &FfiAccountConfig) -> Self {
        Self {
            imap_host: c.imap_host.clone(),
            imap_port: c.imap_port,
            smtp_host: c.smtp_host.clone(),
            smtp_port: c.smtp_port,
            sieve_port: c.sieve_port,
            username: c.username.clone(),
        }
    }
}

/// Auto-config for a PlausiDen mailbox. Delegates entirely to
/// [`AccountConfig::plausiden`] — the single source of truth for PlausiDen's
/// host/port defaults — instead of re-hardcoding them here.
///
/// BUG ASSUMPTION: this is a pure forwarder. If PlausiDen's defaults change,
/// they change in `AccountConfig::plausiden`, not in this crate.
#[uniffi::export]
#[must_use]
pub fn plausiden_account_config(username: String) -> FfiAccountConfig {
    AccountConfig::plausiden("mail.plausiden.com", username).into()
}

// =============================================================================
// Folder / header data records
// =============================================================================

/// A folder summary as returned by [`ThunderCrabClient::list_folders`].
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiFolder {
    /// Folder name as the server presents it.
    pub name: String,
    /// IMAP special-use marker (`\Sent`, `\Drafts`, etc.) if any.
    pub special_use: Option<String>,
    /// Total message count.
    pub messages: u64,
    /// Unread count.
    pub unseen: u64,
}

/// A single additional header captured for rule evaluation. UniFFI cannot
/// represent `(String, String)` tuples, so the core's `Vec<(String, String)>`
/// is bridged to `Vec<FfiHeader>` at this seam.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiHeader {
    /// Header name, lowercased.
    pub name: String,
    /// Header value, original case.
    pub value: String,
}

/// A header-only message summary. HEADER-ONLY by construction — the underlying
/// fetch uses `BODY.PEEK[HEADER]`; no body is ever read.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiHeaders {
    /// IMAP UID.
    pub uid: u32,
    /// Folder this message lives in (server-side path).
    pub folder: String,
    /// `From:` header value.
    pub from: String,
    /// `Subject:` header value.
    pub subject: String,
    /// Additional captured headers (`List-Id`, `List-Unsubscribe`, etc.).
    pub other_headers: Vec<FfiHeader>,
}

// =============================================================================
// SMTP / outbound
// =============================================================================

/// TLS strategy for the SMTP submission connection. Flat mirror of
/// [`thundercrab_imap::smtp::SmtpEncryption`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiSmtpEncryption {
    /// STARTTLS upgrade on the submission port (default 587).
    StartTls,
    /// Implicit TLS from byte 0 (default port 465).
    ImplicitTls,
}

impl From<FfiSmtpEncryption> for SmtpEncryption {
    fn from(e: FfiSmtpEncryption) -> Self {
        match e {
            FfiSmtpEncryption::StartTls => Self::StartTls,
            FfiSmtpEncryption::ImplicitTls => Self::ImplicitTls,
        }
    }
}

/// Outbound message description. Uses owned `String`/`Vec<String>` (UniFFI
/// cannot carry the borrowing `OutboundMessage<'a>`); the borrowed view is
/// rebuilt at the seam right before the send call.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiOutboundMessage {
    /// `From:` mailbox.
    pub from: String,
    /// Recipients on the To: line.
    pub to: Vec<String>,
    /// Recipients on the Cc: line.
    pub cc: Vec<String>,
    /// `Subject:` line.
    pub subject: String,
    /// Plain-text body.
    pub body: String,
}

// =============================================================================
// Flag events
// =============================================================================

/// What the user did. Flat mirror of [`thundercrab_core::FlagSource`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiFlagSource {
    /// User moved a message into a folder.
    ManualMove,
    /// User toggled the "Important" flag (or equivalent).
    ToggleFlag,
    /// User explicitly categorized the message.
    ExplicitCategory,
    /// User accepted a federated suggestion.
    AcceptSuggestion,
}

impl From<FfiFlagSource> for FlagSource {
    fn from(s: FfiFlagSource) -> Self {
        match s {
            FfiFlagSource::ManualMove => Self::ManualMove,
            FfiFlagSource::ToggleFlag => Self::ToggleFlag,
            FfiFlagSource::ExplicitCategory => Self::ExplicitCategory,
            FfiFlagSource::AcceptSuggestion => Self::AcceptSuggestion,
        }
    }
}

/// A flag-event observation. FEATURES ONLY — no body, no full address. The
/// `[u8; 32]` hash is bridged to `Vec<u8>` (validated to length 32 at the
/// seam); the `DateTime<Utc>` is bridged to epoch seconds.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiFlagEvent {
    /// Per-message stable id (32-byte blake3 hash).
    pub message_hash: Vec<u8>,
    /// What the user did.
    pub source: FfiFlagSource,
    /// Destination folder (for moves) or flag name (for toggles).
    pub destination: String,
    /// Sender domain *with* leading `@`. Empty if not parseable.
    pub from_domain_with_at: String,
    /// Lowercased List-Id value (without angle brackets), if present.
    pub list_id: Option<String>,
    /// `true` if a List-Unsubscribe header was present.
    pub has_list_unsubscribe: bool,
    /// Lowercased subject tokens (stop-words removed).
    pub subject_tokens: Vec<String>,
    /// `X-Priority` value if 1 or 2.
    pub priority_high: bool,
    /// When the flag happened, UTC epoch seconds.
    pub observed_at: i64,
}

impl TryFrom<&FfiFlagEvent> for FlagEvent {
    type Error = FfiError;

    fn try_from(e: &FfiFlagEvent) -> Result<Self, Self::Error> {
        let message_hash: [u8; 32] = e
            .message_hash
            .as_slice()
            .try_into()
            .map_err(|_| FfiError::InvalidInput {
                detail: format!(
                    "message_hash must be exactly 32 bytes, got {}",
                    e.message_hash.len()
                ),
            })?;
        let observed_at: DateTime<Utc> =
            Utc.timestamp_opt(e.observed_at, 0).single().ok_or_else(|| {
                FfiError::InvalidInput {
                    detail: format!("observed_at is not a valid epoch second: {}", e.observed_at),
                }
            })?;
        Ok(Self {
            local_id: None,
            message_hash,
            source: e.source.into(),
            destination: e.destination.clone(),
            from_domain_with_at: e.from_domain_with_at.clone(),
            list_id: e.list_id.clone(),
            has_list_unsubscribe: e.has_list_unsubscribe,
            subject_tokens: e.subject_tokens.clone(),
            priority_high: e.priority_high,
            observed_at,
        })
    }
}

// =============================================================================
// Rules
// =============================================================================

/// Where a rule came from. Flat mirror of [`thundercrab_core::RuleOrigin`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiRuleOrigin {
    /// User created or accepted this rule explicitly.
    User,
    /// Shipped with the platform.
    Platform,
    /// Came from the federated suggestion ledger.
    Federated,
}

impl From<FfiRuleOrigin> for RuleOrigin {
    fn from(o: FfiRuleOrigin) -> Self {
        match o {
            FfiRuleOrigin::User => Self::User,
            FfiRuleOrigin::Platform => Self::Platform,
            FfiRuleOrigin::Federated => Self::Federated,
        }
    }
}

impl From<RuleOrigin> for FfiRuleOrigin {
    fn from(o: RuleOrigin) -> Self {
        match o {
            RuleOrigin::User => Self::User,
            RuleOrigin::Platform => Self::Platform,
            RuleOrigin::Federated => Self::Federated,
        }
    }
}

/// A sorting rule at the FFI seam. The `when`/`action` AST is carried as
/// canonical serde JSON strings (`when_json` / `action_json`) so the
/// byte-identical [`MatchExpr`] / [`Action`] AST is produced and consumed by
/// core serde — never re-serialized in Kotlin. This is what keeps the rule
/// wire-compatible with `mail_config::CategoryRule`.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiCrabRule {
    /// Stable id.
    pub id: String,
    /// Human-readable name.
    pub display_name: String,
    /// Match condition, as canonical [`MatchExpr`] JSON.
    pub when_json: String,
    /// Action(s), as canonical [`Action`] JSON.
    pub action_json: String,
    /// Higher = wins.
    pub score: i32,
    /// If `true`, no further rules evaluate after this fires.
    pub stop_on_match: bool,
    /// Provenance.
    pub origin: FfiRuleOrigin,
}

impl TryFrom<&FfiCrabRule> for CrabRule {
    type Error = FfiError;

    fn try_from(r: &FfiCrabRule) -> Result<Self, Self::Error> {
        let when: MatchExpr =
            serde_json::from_str(&r.when_json).map_err(|e| FfiError::InvalidInput {
                detail: format!("when_json: {e}"),
            })?;
        let action: Action =
            serde_json::from_str(&r.action_json).map_err(|e| FfiError::InvalidInput {
                detail: format!("action_json: {e}"),
            })?;
        Ok(Self {
            id: r.id.clone(),
            display_name: r.display_name.clone(),
            when,
            action,
            score: r.score,
            stop_on_match: r.stop_on_match,
            origin: r.origin.into(),
        })
    }
}

impl TryFrom<&CrabRule> for FfiCrabRule {
    type Error = FfiError;

    fn try_from(r: &CrabRule) -> Result<Self, Self::Error> {
        let when_json = serde_json::to_string(&r.when).map_err(|e| FfiError::Protocol {
            detail: format!("serialize when: {e}"),
        })?;
        let action_json = serde_json::to_string(&r.action).map_err(|e| FfiError::Protocol {
            detail: format!("serialize action: {e}"),
        })?;
        Ok(Self {
            id: r.id.clone(),
            display_name: r.display_name.clone(),
            when_json,
            action_json,
            score: r.score,
            stop_on_match: r.stop_on_match,
            origin: r.origin.into(),
        })
    }
}

// =============================================================================
// Synchronous store operations (Db pass-throughs)
// =============================================================================

/// Open the local store at `db_path`, run `f`, close it. The `Db` is not
/// `Send`/long-lived across FFI; each call is a short open-do-close so the
/// store is never held across the boundary.
fn with_db<T>(db_path: &str, f: impl FnOnce(&Db) -> Result<T, FfiError>) -> Result<T, FfiError> {
    let db = Db::open(db_path)?;
    f(&db)
}

/// Record a flag-event observation in the local store.
///
/// # Errors
/// `InvalidInput` if the event's hash/timestamp are malformed; `Protocol` for
/// store failures.
#[uniffi::export]
pub fn record_flag_event(db_path: String, ev: FfiFlagEvent) -> Result<(), FfiError> {
    let event = FlagEvent::try_from(&ev)?;
    with_db(&db_path, |db| {
        db.record_flag(&event)?;
        Ok(())
    })
}

/// Upsert a rule into the local store.
///
/// # Errors
/// `InvalidInput` if the rule's JSON AST is malformed; `Protocol` for store
/// failures.
#[uniffi::export]
pub fn save_rule(db_path: String, rule: FfiCrabRule) -> Result<(), FfiError> {
    let core = CrabRule::try_from(&rule)?;
    with_db(&db_path, |db| {
        db.save_rule(&core)?;
        Ok(())
    })
}

/// Load every rule from the local store, score-desc then id-asc.
///
/// # Errors
/// `Protocol` for store / serialization failures.
#[uniffi::export]
pub fn load_rules(db_path: String) -> Result<Vec<FfiCrabRule>, FfiError> {
    with_db(&db_path, |db| {
        db.load_rules()?
            .iter()
            .map(FfiCrabRule::try_from)
            .collect()
    })
}

/// Delete a rule by id. Returns `true` if a row was removed.
///
/// # Errors
/// `Protocol` for store failures.
#[uniffi::export]
pub fn delete_rule(db_path: String, id: String) -> Result<bool, FfiError> {
    with_db(&db_path, |db| Ok(db.delete_rule(&id)?))
}

/// Render `rules` into a complete personal Sieve script (RFC 5228) ready for
/// [`push_sieve`]. Pure + blocking; performs no I/O.
///
/// The result is a *personal* active script that layers on top of the server's
/// global `sieve_before` (it does not replace server-side category sorting). The
/// emitter is validated against Dovecot's `sievec` in `thundercrab-core`.
///
/// SECURITY: emits only header / Subject / From-domain tests + fileinto/setflag
/// actions; the rule AST has no body-touching variant.
///
/// # Errors
/// `InvalidInput` if any rule's `when_json` / `action_json` is malformed.
#[uniffi::export]
pub fn rules_to_sieve(rules: Vec<FfiCrabRule>) -> Result<String, FfiError> {
    let core: Vec<CrabRule> =
        rules.iter().map(CrabRule::try_from).collect::<Result<_, _>>()?;
    Ok(to_sieve(&core))
}

/// Read-only preview of derived rule suggestions: derives candidates from the
/// local flag-event grouping, then runs each through the suggestion safety gate
/// (`apply_suggestion`), returning only those that pass. No rule is persisted
/// or auto-applied — this is a preview the UI shows for one-click acceptance.
///
/// `min_obs` — drop domain/destination pairs below this observation count.
/// `dominance` — the destination must account for at least this fraction
/// (`0.0..=1.0`) of the domain's events.
///
/// # Errors
/// `Protocol` for store failures; `InvalidInput` if a candidate fails the
/// safety gate or cannot be re-serialized.
#[uniffi::export]
pub fn preview_suggestions(
    db_path: String,
    min_obs: i64,
    dominance: f64,
) -> Result<Vec<FfiCrabRule>, FfiError> {
    with_db(&db_path, |db| {
        let counts = db.flag_counts_by_domain_dest()?;
        let candidates = derive_rule_candidates(&counts, min_obs, dominance);
        let mut out = Vec::with_capacity(candidates.len());
        for cand in &candidates {
            // apply_suggestion both validates (fail-closed on protected
            // folders/flags) and re-marks origin=Federated + clamps score.
            let safe = apply_suggestion(&cand.rule)?;
            out.push(FfiCrabRule::try_from(&safe)?);
        }
        Ok(out)
    })
}

// =============================================================================
// Free-standing network operations (SMTP, ManageSieve)
// =============================================================================

/// Send one message. Connects, authenticates, sends, closes — the password is
/// taken per call and dropped after the send. Pure forwarder to
/// [`thundercrab_imap::smtp::send_message`].
///
/// # Errors
/// `Transport` / `Auth` / `Protocol` from the SMTP layer; `InvalidInput` if an
/// address is unparseable (surfaced by the SMTP layer as `Protocol`).
#[uniffi::export(async_runtime = "tokio")]
pub async fn send_message(
    cfg: FfiAccountConfig,
    password: String,
    encryption: FfiSmtpEncryption,
    message: FfiOutboundMessage,
) -> Result<(), FfiError> {
    let account = AccountConfig::from(&cfg);
    // Rebuild the borrowing OutboundMessage<'a> view from the owned strings.
    let to: Vec<&str> = message.to.iter().map(String::as_str).collect();
    let cc: Vec<&str> = message.cc.iter().map(String::as_str).collect();
    let outbound = OutboundMessage {
        from: message.from.as_str(),
        to: &to,
        cc: &cc,
        subject: message.subject.as_str(),
        body: message.body.as_str(),
    };
    smtp::send_message(&account, &password, encryption.into(), &outbound).await?;
    Ok(())
}

/// Push an active Sieve script via `ManageSieve`. Takes the password and the
/// `script_name` per call — neither is available on the `Backend::put_sieve`
/// trait method (which is `NotImplemented` by design), so this forwards to the
/// standalone [`thundercrab_imap::managesieve::put_active_script`].
///
/// # Errors
/// `Transport` / `Auth` / `Protocol` from the `ManageSieve` layer.
#[uniffi::export(async_runtime = "tokio")]
pub async fn push_sieve(
    cfg: FfiAccountConfig,
    password: String,
    script_name: String,
    script: String,
) -> Result<(), FfiError> {
    let account = AccountConfig::from(&cfg);
    managesieve::put_active_script(&account, &password, &script_name, &script).await?;
    Ok(())
}

// =============================================================================
// IMAP client object (async)
// =============================================================================

/// A live, authenticated IMAP client. Concrete `#[derive(uniffi::Object)]`
/// wrapping the (non-dyn-compatible, RPITIT) [`RustImapBackend`]. The inner
/// backend is held as `Mutex<Option<…>>` so the consuming `logout` can `.take()`
/// it, leaving the object inert afterward.
#[derive(uniffi::Object)]
pub struct ThunderCrabClient {
    inner: Mutex<Option<RustImapBackend>>,
}

/// Connect to the configured IMAPS host and authenticate. The password is
/// consumed and dropped after `LOGIN` (per the real `RustImapBackend::connect`).
/// A free async fn — not a `#[uniffi::constructor]` — because it must return
/// `Result` and does not rely on 0.28's async-constructor support.
///
/// # Errors
/// `Transport` if TCP/TLS/greeting fails; `Auth` if `LOGIN` is rejected.
#[uniffi::export(async_runtime = "tokio")]
pub async fn connect(
    cfg: FfiAccountConfig,
    password: String,
) -> Result<Arc<ThunderCrabClient>, FfiError> {
    let account = AccountConfig::from(&cfg);
    let backend = RustImapBackend::connect(&account, &password).await?;
    Ok(Arc::new(ThunderCrabClient {
        inner: Mutex::new(Some(backend)),
    }))
}

#[uniffi::export(async_runtime = "tokio")]
impl ThunderCrabClient {
    /// List all folders the user can see.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if the client was already
    /// logged out.
    pub async fn list_folders(&self) -> Result<Vec<FfiFolder>, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        let folders = backend.list_folders().await?;
        Ok(folders
            .into_iter()
            .map(|f| FfiFolder {
                name: f.name,
                special_use: f.special_use,
                messages: f.messages,
                unseen: f.unseen,
            })
            .collect())
    }

    /// Fetch headers for messages in `folder`, optionally limited to the most
    /// recent `limit`. HEADER-ONLY (`BODY.PEEK[HEADER]`) — no body is read.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn fetch_headers(
        &self,
        folder: String,
        limit: Option<u32>,
    ) -> Result<Vec<FfiHeaders>, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        let headers = backend.fetch_headers(&folder, limit).await?;
        Ok(headers
            .into_iter()
            .map(|h| FfiHeaders {
                uid: h.uid,
                folder: h.folder,
                from: h.from,
                subject: h.subject,
                other_headers: h
                    .other_headers
                    .into_iter()
                    .map(|(name, value)| FfiHeader { name, value })
                    .collect(),
            })
            .collect())
    }

    /// Move `uid` from `from_folder` to `to_folder` (the IMAP side of a
    /// recorded flag-event move).
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn move_message(
        &self,
        from_folder: String,
        to_folder: String,
        uid: u32,
    ) -> Result<(), FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        backend.move_message(&from_folder, &to_folder, uid).await?;
        Ok(())
    }

    /// Set or clear an IMAP `flag` on `uid` in `folder` (the IMAP side of a
    /// recorded flag-event toggle).
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn set_flag(
        &self,
        folder: String,
        uid: u32,
        flag: String,
        set: bool,
    ) -> Result<(), FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        backend.set_flag(&folder, uid, &flag, set).await?;
        Ok(())
    }

    /// Fetch a message body. NOT IMPLEMENTED: `thundercrab-imap` exposes no
    /// body-reading method, and adding one (a `BODY.PEEK[]` fetch + a MIME
    /// parser) is a display-only carve-out gated on explicit ratification and
    /// walled off from the rules/suggestions/ledger spine. Until then this is a
    /// hard `NotImplemented`.
    ///
    /// # Errors
    /// Always `NotImplemented`.
    #[allow(clippy::unused_async)] // signature parity with the future real impl
    pub async fn fetch_body(&self, _folder: String, _uid: u32) -> Result<String, FfiError> {
        Err(FfiError::NotImplemented {
            detail: "fetch_body: reading message bodies is gated and unimplemented".to_string(),
        })
    }

    /// Log out cleanly. Consumes the inner backend via `.take()`; subsequent
    /// calls on this client return `NotImplemented`. Best-effort — a failed
    /// logout drops the session anyway.
    pub async fn logout(&self) {
        let backend = {
            let mut guard = self.inner.lock().await;
            guard.take()
        };
        if let Some(backend) = backend {
            backend.logout().await;
        }
    }
}

/// `NotImplemented` produced when an operation is attempted on a client whose
/// backend was already taken by `logout`.
fn client_gone() -> FfiError {
    FfiError::NotImplemented {
        detail: "client has been logged out".to_string(),
    }
}

// =============================================================================
// Tests — logic-free seams only (no live IMAP / SMTP / ManageSieve).
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_is_nonempty() {
        assert!(!thundercrab_version().is_empty());
    }

    #[test]
    fn plausiden_config_delegates_to_core() {
        let c = plausiden_account_config("kadyn@plausiden.com".into());
        // Must match AccountConfig::plausiden exactly — no re-hardcoding here.
        let expected = AccountConfig::plausiden("mail.plausiden.com", "kadyn@plausiden.com");
        assert_eq!(c.imap_host, expected.imap_host);
        assert_eq!(c.imap_port, expected.imap_port);
        assert_eq!(c.smtp_host, expected.smtp_host);
        assert_eq!(c.smtp_port, expected.smtp_port);
        assert_eq!(c.sieve_port, expected.sieve_port);
        assert_eq!(c.username, "kadyn@plausiden.com");
    }

    #[test]
    fn account_config_round_trips_through_core() {
        let original = plausiden_account_config("x@plausiden.com".into());
        let core = AccountConfig::from(&original);
        let back = FfiAccountConfig::from(core);
        assert_eq!(back.imap_host, original.imap_host);
        assert_eq!(back.sieve_port, original.sieve_port);
        assert_eq!(back.username, original.username);
    }

    #[test]
    fn backend_error_maps_to_fielded_variants() {
        assert!(matches!(
            FfiError::from(BackendError::Transport("x".into())),
            FfiError::Transport { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::Auth("x".into())),
            FfiError::Auth { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::Protocol("x".into())),
            FfiError::Protocol { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::NotImplemented("x")),
            FfiError::NotImplemented { .. }
        ));
    }

    #[test]
    fn crab_rule_json_round_trips_with_snake_case_tags() {
        let ffi = FfiCrabRule {
            id: "promotions".into(),
            display_name: "Promotions".into(),
            when_json: r#"{"kind":"has_header","header":"List-Unsubscribe"}"#.into(),
            action_json: r#"{"kind":"file_into","folder":"Promotions"}"#.into(),
            score: 80,
            stop_on_match: true,
            origin: FfiRuleOrigin::Platform,
        };
        let core = CrabRule::try_from(&ffi).expect("valid AST parses");
        assert_eq!(core.score, 80);
        // Round-trip back out and confirm the canonical snake_case tags
        // survive (this is the mail_config wire-compat guarantee).
        let back = FfiCrabRule::try_from(&core).expect("re-serializes");
        assert!(back.when_json.contains("\"kind\":\"has_header\""));
        assert!(back.action_json.contains("\"kind\":\"file_into\""));
    }

    #[test]
    fn crab_rule_rejects_malformed_ast() {
        let ffi = FfiCrabRule {
            id: "bad".into(),
            display_name: "Bad".into(),
            when_json: "not json".into(),
            action_json: r#"{"kind":"file_into","folder":"X"}"#.into(),
            score: 1,
            stop_on_match: false,
            origin: FfiRuleOrigin::User,
        };
        assert!(matches!(
            CrabRule::try_from(&ffi),
            Err(FfiError::InvalidInput { .. })
        ));
    }

    #[test]
    fn flag_event_rejects_wrong_length_hash() {
        let ev = FfiFlagEvent {
            message_hash: vec![0u8; 16], // wrong length
            source: FfiFlagSource::ManualMove,
            destination: "Promotions".into(),
            from_domain_with_at: "@x.com".into(),
            list_id: None,
            has_list_unsubscribe: false,
            subject_tokens: vec![],
            priority_high: false,
            observed_at: 0,
        };
        assert!(matches!(
            FlagEvent::try_from(&ev),
            Err(FfiError::InvalidInput { .. })
        ));
    }

    #[test]
    fn flag_event_accepts_valid_hash_and_timestamp() {
        let ev = FfiFlagEvent {
            message_hash: vec![7u8; 32],
            source: FfiFlagSource::ExplicitCategory,
            destination: "Promotions".into(),
            from_domain_with_at: "@mailchimp.com".into(),
            list_id: Some("news.mailchimp.com".into()),
            has_list_unsubscribe: true,
            subject_tokens: vec!["sale".into()],
            priority_high: false,
            observed_at: 1_700_000_000,
        };
        let core = FlagEvent::try_from(&ev).expect("valid event converts");
        assert_eq!(core.message_hash, [7u8; 32]);
        assert_eq!(core.observed_at.timestamp(), 1_700_000_000);
    }

    #[test]
    fn store_record_and_load_round_trip() {
        // Use a temp file DB (Db::open needs a path; :memory: is per-conn and
        // with_db opens a fresh conn each call, so an in-memory DB wouldn't
        // persist across the record/load calls).
        let dir = std::env::temp_dir();
        let path = dir.join(format!("tc_ffi_test_{}.db", std::process::id()));
        let path_str = path.to_string_lossy().to_string();
        let _ = std::fs::remove_file(&path);

        let rule = FfiCrabRule {
            id: "x".into(),
            display_name: "X".into(),
            when_json: r#"{"kind":"always"}"#.into(),
            action_json: r#"{"kind":"file_into","folder":"Forums"}"#.into(),
            score: 75,
            stop_on_match: true,
            origin: FfiRuleOrigin::User,
        };
        save_rule(path_str.clone(), rule).expect("save");
        let loaded = load_rules(path_str.clone()).expect("load");
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].id, "x");
        assert!(delete_rule(path_str.clone(), "x".into()).expect("delete"));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn preview_suggestions_returns_safe_candidates() {
        let dir = std::env::temp_dir();
        let path = dir.join(format!("tc_ffi_sugg_{}.db", std::process::id()));
        let path_str = path.to_string_lossy().to_string();
        let _ = std::fs::remove_file(&path);

        // Record a clear signal: @clear.com → Promotions, 4 distinct events.
        for h in 0..4u8 {
            let ev = FfiFlagEvent {
                message_hash: vec![h; 32],
                source: FfiFlagSource::ManualMove,
                destination: "Promotions".into(),
                from_domain_with_at: "@clear.com".into(),
                list_id: None,
                has_list_unsubscribe: false,
                subject_tokens: vec![],
                priority_high: false,
                observed_at: 1_700_000_000,
            };
            record_flag_event(path_str.clone(), ev).expect("record");
        }
        let suggestions = preview_suggestions(path_str.clone(), 3, 0.7).expect("preview");
        assert_eq!(suggestions.len(), 1);
        // Safety gate re-marks origin=Federated.
        assert!(matches!(suggestions[0].origin, FfiRuleOrigin::Federated));
        assert!(suggestions[0].when_json.contains("@clear.com"));

        let _ = std::fs::remove_file(&path);
    }
}
