//! `thundercrab-ffi` — the UniFFI surface that native UIs (Android Compose
//! first, then a Linux desktop UI) call into. The Rust core stays the single
//! source of truth; this crate is a thin, logic-free pass-through.
//!
//! BUG ASSUMPTION: every function here is a trivial forwarder. If real logic
//! appears in this crate, that's the bug — it belongs in `thundercrab-core`,
//! `thundercrab-imap`, or `thundercrab-suggestions`. The *only* work this
//! layer is allowed to do is shape-translation at the FFI seam: bridging types
//! UniFFI cannot represent (tuples, fixed-size arrays, `DateTime`, the
//! `MatchExpr`/`Action` AST) to/from the canonical core types. No business
//! logic, no rule evaluation, no protocol decisions.
//!
//! SECURITY: nothing here touches message bodies (the core invariant). The
//! exposed surface is config + folder/header-level operations + the rule and
//! flag-event stores. `fetch_body` exists only as a `NotImplemented` stub —
//! reading bodies is gated on explicit ratification and a new IMAP method that
//! does not exist yet (see the stub's docs).
//!
//! Bindings are generated by `uniffi-bindgen` during the platform build
//! (Kotlin for Android, Swift for iOS). See docs/ROADMAP-ANDROID-FIRST.md.

use std::sync::Arc;
use std::time::Instant;

use chrono::{DateTime, TimeZone as _, Utc};
use thundercrab_core::telemetry::{self, DiagCategory, DiagEvent, DiagKind};
use thundercrab_core::{
    Action, CrabRule, Db, FlagEvent, FlagSource, MatchExpr, RuleOrigin, to_sieve,
};
use thundercrab_imap::idle::{self, IdleWatcher};
use thundercrab_imap::rust_imap::RustImapBackend;
use thundercrab_imap::smtp::{self, OutboundMessage, SmtpEncryption};
use thundercrab_imap::{AccountConfig, Backend as _, BackendError, CryptoMode, managesieve};
use thundercrab_suggestions::{apply_suggestion, derive_rule_candidates};
use tokio::sync::Mutex;

uniffi::setup_scaffolding!();

/// Overall wall-clock bound for a cold-flow network operation (TCP connect +
/// TLS handshake + auth + protocol reads). thundercrab-imap bounds the TCP
/// connect itself; this caps the WHOLE flow so a server that completes the TCP
/// connect and then STALLS mid-handshake/auth can't hang the mobile UI. SMTP is
/// already bounded by lettre's own timeout, so only IMAP connect + ManageSieve
/// push need this wrapper.
const OP_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(45);

// =============================================================================
// Errors
// =============================================================================

/// Errors surfaced across the FFI boundary. Maps the backend / store / parse
/// failure space onto a flat, fielded enum that UniFFI renders as a Kotlin
/// sealed class. Each variant carries a human-readable detail string.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum FfiError {
    /// Network or TLS transport failure.
    #[error("transport: {detail}")]
    Transport {
        /// Human-readable detail.
        detail: String,
    },
    /// Authentication or authorization failure.
    #[error("auth: {detail}")]
    Auth {
        /// Human-readable detail.
        detail: String,
    },
    /// Server returned a protocol-level error, or a JSON/store error occurred.
    #[error("protocol: {detail}")]
    Protocol {
        /// Human-readable detail.
        detail: String,
    },
    /// The requested operation is not implemented in this build.
    #[error("not implemented: {detail}")]
    NotImplemented {
        /// Human-readable detail.
        detail: String,
    },
    /// A value handed across the FFI seam was malformed (bad JSON, wrong-length
    /// hash, unparseable address, etc.).
    #[error("invalid input: {detail}")]
    InvalidInput {
        /// Human-readable detail.
        detail: String,
    },
}

impl From<BackendError> for FfiError {
    fn from(e: BackendError) -> Self {
        match e {
            BackendError::Transport(m) => Self::Transport { detail: m },
            BackendError::Auth(m) => Self::Auth { detail: m },
            BackendError::Protocol(m) => Self::Protocol { detail: m },
            BackendError::NotImplemented(m) => Self::NotImplemented {
                detail: m.to_string(),
            },
        }
    }
}

impl From<thundercrab_core::DbError> for FfiError {
    fn from(e: thundercrab_core::DbError) -> Self {
        // The store's failure modes are all "the backing protocol said no";
        // they map onto Protocol so the UI's catch-all handles them.
        Self::Protocol {
            detail: e.to_string(),
        }
    }
}

impl From<thundercrab_suggestions::SafetyError> for FfiError {
    fn from(e: thundercrab_suggestions::SafetyError) -> Self {
        Self::InvalidInput {
            detail: e.to_string(),
        }
    }
}

// =============================================================================
// Diagnostics (privacy-safe telemetry)
// =============================================================================

/// Map an [`FfiError`] onto a PII-free [`DiagCategory`]. The arms read only the
/// variant and our *own* static detail prefixes ("…timed out", "tls …") — never
/// user data — so classification leaks nothing off-device.
fn ffi_category(e: &FfiError) -> DiagCategory {
    match e {
        FfiError::Auth { .. } => DiagCategory::Auth,
        FfiError::Protocol { .. } => DiagCategory::Protocol,
        FfiError::NotImplemented { .. } => DiagCategory::NotImplemented,
        FfiError::InvalidInput { .. } => DiagCategory::Internal,
        FfiError::Transport { detail } => {
            if detail.contains("timed out") {
                DiagCategory::Timeout
            } else if detail.contains("tls") {
                DiagCategory::Tls
            } else {
                DiagCategory::Transport
            }
        }
    }
}

// =============================================================================
// On-device error ring + client breadcrumbs (diagnostics report source)
// =============================================================================
//
// The DiagEvent ring stays PII-free by design (it can be exported as
// telemetry). This SECOND ring keeps the actual error strings and UI
// breadcrumbs — it never leaves the device except inside an explicit,
// user-initiated diagnostics report appended to the user's OWN mailbox.

/// Max entries retained in the error/breadcrumb ring.
const ERROR_RING_CAP: usize = 100;

/// (unix ms, source op, detail line).
static ERROR_RING: std::sync::LazyLock<std::sync::Mutex<std::collections::VecDeque<(u64, String, String)>>> =
    std::sync::LazyLock::new(|| std::sync::Mutex::new(std::collections::VecDeque::new()));

fn now_unix_ms() -> u64 {
    u64::try_from(chrono::Utc::now().timestamp_millis()).unwrap_or(0)
}

/// Record one line into the on-device error/breadcrumb ring.
fn record_error_line(op: &str, detail: &str) {
    let mut ring = ERROR_RING.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
    if ring.len() >= ERROR_RING_CAP {
        ring.pop_front();
    }
    ring.push_back((now_unix_ms(), op.to_string(), detail.to_string()));
}

/// Record a client-side breadcrumb (e.g. `"MessageList INBOX: showed 0 rows"`).
/// Native UIs call this at interesting state transitions so a diagnostics
/// report can reconstruct WHAT THE USER SAW, not just what the wire did.
/// Stored on-device only (see the ring's privacy note).
#[uniffi::export]
pub fn log_client_event(line: String) {
    tracing::info!(target: "thundercrab_ffi::client", "{line}");
    record_error_line("ui", &line);
}

/// Initialize logging for the host platform. On Android, routes all `tracing`
/// output (this crate + the Rust core) to logcat under the `ThunderCrab` tag —
/// so `adb logcat -s ThunderCrab` (or a bug report) shows the full pipeline.
/// `verbose` selects debug-level detail; changing it requires an app restart
/// (the subscriber installs once per process).
#[uniffi::export]
pub fn init_logging(verbose: bool) {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        let filter = if verbose {
            "info,thundercrab_ffi=debug,thundercrab_imap=debug,thundercrab_core=debug,thundercrab_suggestions=debug"
        } else {
            "info"
        };
        #[cfg(target_os = "android")]
        {
            use tracing_subscriber::layer::SubscriberExt;
            use tracing_subscriber::util::SubscriberInitExt;
            if let Ok(layer) = tracing_android::layer("ThunderCrab") {
                let _ = tracing_subscriber::registry()
                    .with(tracing_subscriber::EnvFilter::new(filter))
                    .with(layer)
                    .try_init();
            }
        }
        #[cfg(not(target_os = "android"))]
        {
            let _ = tracing_subscriber::fmt()
                .with_env_filter(tracing_subscriber::EnvFilter::new(filter))
                .with_target(false)
                .compact()
                .try_init();
        }
    });
}

/// Time an async operation and record exactly one [`DiagEvent`] for its outcome.
/// `count_of` extracts the primary count from a success value (e.g. folders
/// listed); failures record category-only, never the error string. This is the
/// single instrumentation point for the network surface.
async fn timed<T, Fut>(
    op: &'static str,
    ok: DiagKind,
    fail: DiagKind,
    count_of: impl Fn(&T) -> u64,
    fut: Fut,
) -> Result<T, FfiError>
where
    Fut: std::future::Future<Output = Result<T, FfiError>>,
{
    let start = Instant::now();
    let res = fut.await;
    let ms = u64::try_from(start.elapsed().as_millis()).unwrap_or(u64::MAX);
    match &res {
        Ok(v) => telemetry::record_event(ok, DiagCategory::None, op, count_of(v), 0, ms),
        Err(e) => {
            telemetry::record_event(fail, ffi_category(e), op, 0, 0, ms);
            // Full error text goes to the ON-DEVICE ring only (see its privacy
            // note) so a diagnostics report can explain WHY the op failed.
            record_error_line(op, &e.to_string());
        }
    }
    res
}

/// A diagnostic event flattened for the FFI: the Rust enums are stringified
/// (their stable `Debug` names) so the UI needs no parallel enum on the binding
/// side. PII-free — the type has no field that could hold user data.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiDiagEvent {
    /// [`DiagKind`] name (e.g. `"ConnectFail"`).
    pub kind: String,
    /// [`DiagCategory`] name (e.g. `"Auth"`).
    pub category: String,
    /// Stable numeric code (`kind * 1000 + category`).
    pub code: u32,
    /// Static operation label (e.g. `"list_folders"`).
    pub op: String,
    /// Primary count (folders listed, headers fetched, …).
    pub count: u64,
    /// Secondary count (folders skipped, retries, …).
    pub extra: u64,
    /// Operation duration in milliseconds.
    pub duration_ms: u64,
    /// Event time, milliseconds since the Unix epoch.
    pub at_unix_ms: u64,
}

impl From<DiagEvent> for FfiDiagEvent {
    fn from(e: DiagEvent) -> Self {
        Self {
            kind: format!("{:?}", e.kind),
            category: format!("{:?}", e.category),
            code: e.code,
            op: e.op.to_string(),
            count: e.count,
            extra: e.extra,
            duration_ms: e.duration_ms,
            at_unix_ms: e.at_unix_ms,
        }
    }
}

/// Copy out recent diagnostic events without clearing them (for the in-app
/// diagnostics screen / "what would be sent" preview).
#[uniffi::export]
#[must_use]
pub fn diagnostics_snapshot() -> Vec<FfiDiagEvent> {
    telemetry::snapshot().into_iter().map(Into::into).collect()
}

/// Take and clear all buffered diagnostic events (so an upload does not re-send
/// what it already shipped).
#[uniffi::export]
#[must_use]
pub fn diagnostics_drain() -> Vec<FfiDiagEvent> {
    telemetry::drain().into_iter().map(Into::into).collect()
}

/// Discard all buffered diagnostic events (e.g. when the user declines or
/// disables telemetry).
#[uniffi::export]
pub fn diagnostics_clear() {
    telemetry::clear();
}

/// Recent diagnostic events serialized as a JSON array — the exact, auditable
/// payload an upload would send, so the UI can show "here is what we send".
#[uniffi::export]
#[must_use]
pub fn diagnostics_json() -> String {
    telemetry::to_json(&telemetry::snapshot())
}

/// Master switch for diagnostics. The app calls this at startup with its
/// build-type flag (off for production releases) and again whenever the user
/// toggles telemetry in settings. When off, nothing is collected or buffered.
#[uniffi::export]
pub fn telemetry_set_enabled(on: bool) {
    telemetry::set_enabled(on);
}

/// Whether diagnostic collection is currently enabled.
#[uniffi::export]
#[must_use]
pub fn telemetry_is_enabled() -> bool {
    telemetry::is_enabled()
}

// =============================================================================
// Version
// =============================================================================

/// Library version, surfaced to the UI's About screen.
#[uniffi::export]
#[must_use]
pub fn thundercrab_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// =============================================================================
// Account config
// =============================================================================

/// Post-quantum key-exchange posture, surfaced to the UI's security settings.
/// Mirrors [`thundercrab_imap::CryptoMode`].
#[derive(uniffi::Enum, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum FfiCryptoMode {
    /// Post-quantum hybrid preferred, classical fallback (recommended default).
    #[default]
    PqHybrid,
    /// Classical key exchange only (maximum compatibility).
    ClassicalOnly,
    /// Require a post-quantum hybrid group — fail rather than fall back.
    PqRequired,
}

impl From<FfiCryptoMode> for CryptoMode {
    fn from(m: FfiCryptoMode) -> Self {
        match m {
            FfiCryptoMode::PqHybrid => Self::PqHybrid,
            FfiCryptoMode::ClassicalOnly => Self::ClassicalOnly,
            FfiCryptoMode::PqRequired => Self::PqRequired,
        }
    }
}

impl From<CryptoMode> for FfiCryptoMode {
    fn from(m: CryptoMode) -> Self {
        match m {
            CryptoMode::PqHybrid => Self::PqHybrid,
            CryptoMode::ClassicalOnly => Self::ClassicalOnly,
            CryptoMode::PqRequired => Self::PqRequired,
        }
    }
}

/// Connection settings a mail app needs, mirroring the canonical
/// [`thundercrab_imap::AccountConfig`] field-for-field. Returned to the
/// platform UI so the account-setup screen can be pre-filled instead of asking
/// the user to know ports.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiAccountConfig {
    /// Hostname for IMAP and `ManageSieve`.
    pub imap_host: String,
    /// IMAPS port.
    pub imap_port: u16,
    /// SMTP submission host.
    pub smtp_host: String,
    /// SMTP submission port.
    pub smtp_port: u16,
    /// `ManageSieve` port.
    pub sieve_port: u16,
    /// Username (full email address).
    pub username: String,
    /// Post-quantum key-exchange posture for this account's TLS connections.
    pub crypto_mode: FfiCryptoMode,
}

impl From<AccountConfig> for FfiAccountConfig {
    fn from(c: AccountConfig) -> Self {
        Self {
            imap_host: c.imap_host,
            imap_port: c.imap_port,
            smtp_host: c.smtp_host,
            smtp_port: c.smtp_port,
            sieve_port: c.sieve_port,
            username: c.username,
            crypto_mode: c.crypto_mode.into(),
        }
    }
}

impl From<&FfiAccountConfig> for AccountConfig {
    fn from(c: &FfiAccountConfig) -> Self {
        Self {
            imap_host: c.imap_host.clone(),
            imap_port: c.imap_port,
            smtp_host: c.smtp_host.clone(),
            smtp_port: c.smtp_port,
            sieve_port: c.sieve_port,
            username: c.username.clone(),
            crypto_mode: c.crypto_mode.into(),
        }
    }
}

/// Auto-config for a PlausiDen mailbox. Delegates entirely to
/// [`AccountConfig::plausiden`] — the single source of truth for PlausiDen's
/// host/port defaults — instead of re-hardcoding them here.
///
/// BUG ASSUMPTION: this is a pure forwarder. If PlausiDen's defaults change,
/// they change in `AccountConfig::plausiden`, not in this crate.
#[uniffi::export]
#[must_use]
pub fn plausiden_account_config(username: String) -> FfiAccountConfig {
    AccountConfig::plausiden("mail.plausiden.com", username).into()
}

/// Render a ThunderCrab Markdown compose body to sanitized, display-safe HTML —
/// the `text/html` part of an outgoing message (pair it with the Markdown
/// source as the `text/plain` body). CommonMark + safe extensions, run through
/// the same sanitizer as received mail: no scripts, no remote content, no JS.
/// Pure and deterministic; safe to call on the UI thread.
#[uniffi::export]
#[must_use]
pub fn render_markdown(markdown: String) -> String {
    thundercrab_core::mail_html::markdown_to_safe_html(&markdown)
}

// =============================================================================
// Folder / header data records
// =============================================================================

/// A folder summary as returned by [`ThunderCrabClient::list_folders`].
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiFolder {
    /// Folder name as the server presents it.
    pub name: String,
    /// IMAP special-use marker (`\Sent`, `\Drafts`, etc.) if any.
    pub special_use: Option<String>,
    /// Total message count.
    pub messages: u64,
    /// Unread count.
    pub unseen: u64,
}

/// A single additional header captured for rule evaluation. UniFFI cannot
/// represent `(String, String)` tuples, so the core's `Vec<(String, String)>`
/// is bridged to `Vec<FfiHeader>` at this seam.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiHeader {
    /// Header name, lowercased.
    pub name: String,
    /// Header value, original case.
    pub value: String,
}

/// A header-only message summary. HEADER-ONLY by construction — the underlying
/// fetch uses `BODY.PEEK[HEADER]`; no body is ever read.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiHeaders {
    /// IMAP UID.
    pub uid: u32,
    /// Folder this message lives in (server-side path).
    pub folder: String,
    /// `From:` header value.
    pub from: String,
    /// `Subject:` header value.
    pub subject: String,
    /// Additional captured headers (`List-Id`, `List-Unsubscribe`, etc.).
    pub other_headers: Vec<FfiHeader>,
    /// If the sender requested a read receipt (RFC 8098), the address it should
    /// go to; otherwise null. The UI surfaces this; ThunderCrab never
    /// auto-responds.
    pub read_receipt_requested: Option<String>,
}

/// A received message's display body. The HTML part is ALREADY SANITIZED by the
/// core (scripts, event handlers, and all remote content removed) — safe to
/// render directly (e.g. in a `WebView`). Either part may be null.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiMessageBody {
    /// Plain-text body, if present.
    pub plain: Option<String>,
    /// Sanitized HTML body (a real text/html part, or the text converted to
    /// HTML), safe to render. Null only when there is no renderable body.
    pub html_sanitized: Option<String>,
    /// Attachment metadata, in document order. Bytes are NOT included here (to
    /// keep this payload light) — fetch them on demand with `fetch_attachment`
    /// using the attachment's index in this list.
    pub attachments: Vec<FfiAttachment>,
}

/// Metadata for one attachment. Bytes are fetched separately via
/// [`ThunderCrabClient::fetch_attachment`] so listing a message body stays cheap
/// even when it carries large files.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiAttachment {
    /// Declared filename; empty when the part is unnamed.
    pub filename: String,
    /// MIME type as `type/subtype` (e.g. `image/png`).
    pub mime_type: String,
    /// Decoded size in bytes.
    pub size: u64,
}

// =============================================================================
// SMTP / outbound
// =============================================================================

/// TLS strategy for the SMTP submission connection. Flat mirror of
/// [`thundercrab_imap::smtp::SmtpEncryption`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiSmtpEncryption {
    /// STARTTLS upgrade on the submission port (default 587).
    StartTls,
    /// Implicit TLS from byte 0 (default port 465).
    ImplicitTls,
}

impl From<FfiSmtpEncryption> for SmtpEncryption {
    fn from(e: FfiSmtpEncryption) -> Self {
        match e {
            FfiSmtpEncryption::StartTls => Self::StartTls,
            FfiSmtpEncryption::ImplicitTls => Self::ImplicitTls,
        }
    }
}

/// Outbound message description. Uses owned `String`/`Vec<String>` (UniFFI
/// cannot carry the borrowing `OutboundMessage<'a>`); the borrowed view is
/// rebuilt at the seam right before the send call.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiOutboundMessage {
    /// `From:` mailbox.
    pub from: String,
    /// Recipients on the To: line.
    pub to: Vec<String>,
    /// Recipients on the Cc: line.
    pub cc: Vec<String>,
    /// `Subject:` line.
    pub subject: String,
    /// Plain-text body — always sent (the universal fallback / whole message
    /// when `html_body` is null). For a Markdown compose, pass the Markdown
    /// source here; it reads fine in any plain-text client.
    pub body: String,
    /// Optional HTML body. When present the message is sent as
    /// `multipart/alternative` so HTML-capable clients render it and others
    /// fall back to `body`. The caller is responsible for sanitizing it.
    pub html_body: Option<String>,
    /// When set, request a read receipt (RFC 8098) to this address — usually
    /// the sender's own. Opt-in per message; null requests nothing.
    pub read_receipt_to: Option<String>,
    /// RFC 5322 `Message-ID` of the message being replied to (with angle
    /// brackets). Set on a reply to emit `In-Reply-To:`; null otherwise.
    pub in_reply_to: Option<String>,
    /// Space-separated ancestor `Message-ID` chain for the `References:` header
    /// (RFC 5322 §3.6.4). Null omits it.
    pub references: Option<String>,
    /// Files to attach. When non-empty, the whole message is wrapped in
    /// `multipart/mixed` (body first, then each attachment). Empty = no change.
    pub attachments: Vec<FfiOutboundAttachment>,
}

/// One outgoing attachment crossing the FFI seam: owned bytes plus their label.
/// `bytes` surfaces to Kotlin as `ByteArray`. Mirrors
/// [`thundercrab_imap::smtp::OutboundAttachment`], which borrows instead.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiOutboundAttachment {
    /// Filename shown to the recipient (Content-Disposition `filename`).
    pub filename: String,
    /// MIME type as `type/subtype`; falls back to `application/octet-stream`
    /// in the SMTP layer when it can't be parsed.
    pub mime_type: String,
    /// The raw file bytes.
    pub bytes: Vec<u8>,
}

// =============================================================================
// Flag events
// =============================================================================

/// What the user did. Flat mirror of [`thundercrab_core::FlagSource`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiFlagSource {
    /// User moved a message into a folder.
    ManualMove,
    /// User toggled the "Important" flag (or equivalent).
    ToggleFlag,
    /// User explicitly categorized the message.
    ExplicitCategory,
    /// User accepted a federated suggestion.
    AcceptSuggestion,
}

impl From<FfiFlagSource> for FlagSource {
    fn from(s: FfiFlagSource) -> Self {
        match s {
            FfiFlagSource::ManualMove => Self::ManualMove,
            FfiFlagSource::ToggleFlag => Self::ToggleFlag,
            FfiFlagSource::ExplicitCategory => Self::ExplicitCategory,
            FfiFlagSource::AcceptSuggestion => Self::AcceptSuggestion,
        }
    }
}

/// A flag-event observation. FEATURES ONLY — no body, no full address. The
/// `[u8; 32]` hash is bridged to `Vec<u8>` (validated to length 32 at the
/// seam); the `DateTime<Utc>` is bridged to epoch seconds.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiFlagEvent {
    /// Per-message stable id (32-byte blake3 hash).
    pub message_hash: Vec<u8>,
    /// What the user did.
    pub source: FfiFlagSource,
    /// Destination folder (for moves) or flag name (for toggles).
    pub destination: String,
    /// Sender domain *with* leading `@`. Empty if not parseable.
    pub from_domain_with_at: String,
    /// Lowercased List-Id value (without angle brackets), if present.
    pub list_id: Option<String>,
    /// `true` if a List-Unsubscribe header was present.
    pub has_list_unsubscribe: bool,
    /// Lowercased subject tokens (stop-words removed).
    pub subject_tokens: Vec<String>,
    /// `X-Priority` value if 1 or 2.
    pub priority_high: bool,
    /// When the flag happened, UTC epoch seconds.
    pub observed_at: i64,
}

impl TryFrom<&FfiFlagEvent> for FlagEvent {
    type Error = FfiError;

    fn try_from(e: &FfiFlagEvent) -> Result<Self, Self::Error> {
        let message_hash: [u8; 32] = e
            .message_hash
            .as_slice()
            .try_into()
            .map_err(|_| FfiError::InvalidInput {
                detail: format!(
                    "message_hash must be exactly 32 bytes, got {}",
                    e.message_hash.len()
                ),
            })?;
        let observed_at: DateTime<Utc> =
            Utc.timestamp_opt(e.observed_at, 0).single().ok_or_else(|| {
                FfiError::InvalidInput {
                    detail: format!("observed_at is not a valid epoch second: {}", e.observed_at),
                }
            })?;
        Ok(Self {
            local_id: None,
            message_hash,
            source: e.source.into(),
            destination: e.destination.clone(),
            from_domain_with_at: e.from_domain_with_at.clone(),
            list_id: e.list_id.clone(),
            has_list_unsubscribe: e.has_list_unsubscribe,
            subject_tokens: e.subject_tokens.clone(),
            priority_high: e.priority_high,
            observed_at,
        })
    }
}

// =============================================================================
// Rules
// =============================================================================

/// Where a rule came from. Flat mirror of [`thundercrab_core::RuleOrigin`].
#[derive(uniffi::Enum, Clone, Copy, Debug)]
pub enum FfiRuleOrigin {
    /// User created or accepted this rule explicitly.
    User,
    /// Shipped with the platform.
    Platform,
    /// Came from the federated suggestion ledger.
    Federated,
}

impl From<FfiRuleOrigin> for RuleOrigin {
    fn from(o: FfiRuleOrigin) -> Self {
        match o {
            FfiRuleOrigin::User => Self::User,
            FfiRuleOrigin::Platform => Self::Platform,
            FfiRuleOrigin::Federated => Self::Federated,
        }
    }
}

impl From<RuleOrigin> for FfiRuleOrigin {
    fn from(o: RuleOrigin) -> Self {
        match o {
            RuleOrigin::User => Self::User,
            RuleOrigin::Platform => Self::Platform,
            RuleOrigin::Federated => Self::Federated,
        }
    }
}

/// A sorting rule at the FFI seam. The `when`/`action` AST is carried as
/// canonical serde JSON strings (`when_json` / `action_json`) so the
/// byte-identical [`MatchExpr`] / [`Action`] AST is produced and consumed by
/// core serde — never re-serialized in Kotlin. This is what keeps the rule
/// wire-compatible with `mail_config::CategoryRule`.
#[derive(uniffi::Record, Clone, Debug)]
pub struct FfiCrabRule {
    /// Stable id.
    pub id: String,
    /// Human-readable name.
    pub display_name: String,
    /// Match condition, as canonical [`MatchExpr`] JSON.
    pub when_json: String,
    /// Action(s), as canonical [`Action`] JSON.
    pub action_json: String,
    /// Higher = wins.
    pub score: i32,
    /// If `true`, no further rules evaluate after this fires.
    pub stop_on_match: bool,
    /// Provenance.
    pub origin: FfiRuleOrigin,
}

impl TryFrom<&FfiCrabRule> for CrabRule {
    type Error = FfiError;

    fn try_from(r: &FfiCrabRule) -> Result<Self, Self::Error> {
        let when: MatchExpr =
            serde_json::from_str(&r.when_json).map_err(|e| FfiError::InvalidInput {
                detail: format!("when_json: {e}"),
            })?;
        let action: Action =
            serde_json::from_str(&r.action_json).map_err(|e| FfiError::InvalidInput {
                detail: format!("action_json: {e}"),
            })?;
        Ok(Self {
            id: r.id.clone(),
            display_name: r.display_name.clone(),
            when,
            action,
            score: r.score,
            stop_on_match: r.stop_on_match,
            origin: r.origin.into(),
        })
    }
}

impl TryFrom<&CrabRule> for FfiCrabRule {
    type Error = FfiError;

    fn try_from(r: &CrabRule) -> Result<Self, Self::Error> {
        let when_json = serde_json::to_string(&r.when).map_err(|e| FfiError::Protocol {
            detail: format!("serialize when: {e}"),
        })?;
        let action_json = serde_json::to_string(&r.action).map_err(|e| FfiError::Protocol {
            detail: format!("serialize action: {e}"),
        })?;
        Ok(Self {
            id: r.id.clone(),
            display_name: r.display_name.clone(),
            when_json,
            action_json,
            score: r.score,
            stop_on_match: r.stop_on_match,
            origin: r.origin.into(),
        })
    }
}

// =============================================================================
// Synchronous store operations (Db pass-throughs)
// =============================================================================

/// Open the local store at `db_path`, run `f`, close it. The `Db` is not
/// `Send`/long-lived across FFI; each call is a short open-do-close so the
/// store is never held across the boundary.
fn with_db<T>(db_path: &str, f: impl FnOnce(&Db) -> Result<T, FfiError>) -> Result<T, FfiError> {
    let db = Db::open(db_path)?;
    f(&db)
}

/// Record a flag-event observation in the local store.
///
/// # Errors
/// `InvalidInput` if the event's hash/timestamp are malformed; `Protocol` for
/// store failures.
#[uniffi::export]
pub fn record_flag_event(db_path: String, ev: FfiFlagEvent) -> Result<(), FfiError> {
    let event = FlagEvent::try_from(&ev)?;
    with_db(&db_path, |db| {
        db.record_flag(&event)?;
        Ok(())
    })
}

/// Upsert a rule into the local store.
///
/// # Errors
/// `InvalidInput` if the rule's JSON AST is malformed; `Protocol` for store
/// failures.
#[uniffi::export]
pub fn save_rule(db_path: String, rule: FfiCrabRule) -> Result<(), FfiError> {
    let core = CrabRule::try_from(&rule)?;
    with_db(&db_path, |db| {
        db.save_rule(&core)?;
        Ok(())
    })
}

/// Load every rule from the local store, score-desc then id-asc.
///
/// # Errors
/// `Protocol` for store / serialization failures.
#[uniffi::export]
pub fn load_rules(db_path: String) -> Result<Vec<FfiCrabRule>, FfiError> {
    with_db(&db_path, |db| {
        db.load_rules()?
            .iter()
            .map(FfiCrabRule::try_from)
            .collect()
    })
}

/// Delete a rule by id. Returns `true` if a row was removed.
///
/// # Errors
/// `Protocol` for store failures.
#[uniffi::export]
pub fn delete_rule(db_path: String, id: String) -> Result<bool, FfiError> {
    with_db(&db_path, |db| Ok(db.delete_rule(&id)?))
}

/// Render `rules` into a complete personal Sieve script (RFC 5228) ready for
/// [`push_sieve`]. Pure + blocking; performs no I/O.
///
/// The result is a *personal* active script that layers on top of the server's
/// global `sieve_before` (it does not replace server-side category sorting). The
/// emitter is validated against Dovecot's `sievec` in `thundercrab-core`.
///
/// SECURITY: emits only header / Subject / From-domain tests + fileinto/setflag
/// actions; the rule AST has no body-touching variant.
///
/// # Errors
/// `InvalidInput` if any rule's `when_json` / `action_json` is malformed.
#[uniffi::export]
pub fn rules_to_sieve(rules: Vec<FfiCrabRule>) -> Result<String, FfiError> {
    let core: Vec<CrabRule> =
        rules.iter().map(CrabRule::try_from).collect::<Result<_, _>>()?;
    Ok(to_sieve(&core))
}

/// Read-only preview of derived rule suggestions: derives candidates from the
/// local flag-event grouping, then runs each through the suggestion safety gate
/// (`apply_suggestion`), returning only those that pass. No rule is persisted
/// or auto-applied — this is a preview the UI shows for one-click acceptance.
///
/// `min_obs` — drop domain/destination pairs below this observation count.
/// `dominance` — the destination must account for at least this fraction
/// (`0.0..=1.0`) of the domain's events.
///
/// # Errors
/// `Protocol` for store failures; `InvalidInput` if a candidate fails the
/// safety gate or cannot be re-serialized.
#[uniffi::export]
pub fn preview_suggestions(
    db_path: String,
    min_obs: i64,
    dominance: f64,
) -> Result<Vec<FfiCrabRule>, FfiError> {
    with_db(&db_path, |db| {
        let counts = db.flag_counts_by_domain_dest()?;
        let candidates = derive_rule_candidates(&counts, min_obs, dominance);
        let mut out = Vec::with_capacity(candidates.len());
        for cand in &candidates {
            // apply_suggestion validates (fail-closed on protected folders/flags)
            // and re-marks origin=Federated + clamps score. A candidate that FAILS
            // the gate is SKIPPED — preview returns only those that pass, and never
            // errors the whole batch over a single unsafe candidate (its doc
            // contract). A real serialization failure on a *safe* rule still errors.
            let Ok(safe) = apply_suggestion(&cand.rule) else { continue };
            out.push(FfiCrabRule::try_from(&safe)?);
        }
        Ok(out)
    })
}

// =============================================================================
// Free-standing network operations (SMTP, ManageSieve)
// =============================================================================

/// Send one message. Connects, authenticates, sends, closes — the password is
/// taken per call and dropped after the send. Pure forwarder to
/// [`thundercrab_imap::smtp::send_message`].
///
/// # Errors
/// `Transport` / `Auth` / `Protocol` from the SMTP layer; `InvalidInput` if an
/// address is unparseable (surfaced by the SMTP layer as `Protocol`).
#[uniffi::export(async_runtime = "tokio")]
pub async fn send_message(
    cfg: FfiAccountConfig,
    password: String,
    encryption: FfiSmtpEncryption,
    message: FfiOutboundMessage,
) -> Result<(), FfiError> {
    let account = AccountConfig::from(&cfg);
    // Rebuild the borrowing OutboundMessage<'a> view from the owned strings.
    let to: Vec<&str> = message.to.iter().map(String::as_str).collect();
    let cc: Vec<&str> = message.cc.iter().map(String::as_str).collect();
    // Rebuild the borrowing attachment views from the owned FFI records.
    let attachments: Vec<smtp::OutboundAttachment> = message
        .attachments
        .iter()
        .map(|a| smtp::OutboundAttachment {
            filename: a.filename.as_str(),
            mime_type: a.mime_type.as_str(),
            bytes: a.bytes.as_slice(),
        })
        .collect();
    let outbound = OutboundMessage {
        from: message.from.as_str(),
        to: &to,
        cc: &cc,
        subject: message.subject.as_str(),
        body: message.body.as_str(),
        html_body: message.html_body.as_deref(),
        read_receipt_to: message.read_receipt_to.as_deref(),
        in_reply_to: message.in_reply_to.as_deref(),
        references: message.references.as_deref(),
        attachments: &attachments,
    };
    timed(
        "send_message",
        DiagKind::SendOk,
        DiagKind::SendFail,
        |_: &()| 0,
        async {
            smtp::send_message(&account, &password, encryption.into(), &outbound).await?;
            Ok(())
        },
    )
    .await
}

/// Push an active Sieve script via `ManageSieve`. Takes the password and the
/// `script_name` per call — neither is available on the `Backend::put_sieve`
/// trait method (which is `NotImplemented` by design), so this forwards to the
/// standalone [`thundercrab_imap::managesieve::put_active_script`].
///
/// # Errors
/// `Transport` / `Auth` / `Protocol` from the `ManageSieve` layer.
#[uniffi::export(async_runtime = "tokio")]
pub async fn push_sieve(
    cfg: FfiAccountConfig,
    password: String,
    script_name: String,
    script: String,
) -> Result<(), FfiError> {
    let account = AccountConfig::from(&cfg);
    timed(
        "push_sieve",
        DiagKind::SievePushOk,
        DiagKind::SievePushFail,
        |_: &()| 0,
        async {
            tokio::time::timeout(
                OP_TIMEOUT,
                managesieve::put_active_script(&account, &password, &script_name, &script),
            )
            .await
            .map_err(|_| FfiError::Transport {
                detail: "push_sieve timed out".to_string(),
            })??;
            Ok(())
        },
    )
    .await
}

// =============================================================================
// IMAP client object (async)
// =============================================================================

/// A live, authenticated IMAP client. Concrete `#[derive(uniffi::Object)]`
/// wrapping the (non-dyn-compatible, RPITIT) [`RustImapBackend`]. The inner
/// backend is held as `Mutex<Option<…>>` so the consuming `logout` can `.take()`
/// it, leaving the object inert afterward.
#[derive(uniffi::Object)]
pub struct ThunderCrabClient {
    inner: Mutex<Option<RustImapBackend>>,
}

/// Connect to the configured IMAPS host and authenticate. The password is
/// consumed and dropped after `LOGIN` (per the real `RustImapBackend::connect`).
/// A free async fn — not a `#[uniffi::constructor]` — because it must return
/// `Result` and does not rely on 0.28's async-constructor support.
///
/// # Errors
/// `Transport` if TCP/TLS/greeting fails; `Auth` if `LOGIN` is rejected.
#[uniffi::export(async_runtime = "tokio")]
pub async fn connect(
    cfg: FfiAccountConfig,
    password: String,
) -> Result<Arc<ThunderCrabClient>, FfiError> {
    let account = AccountConfig::from(&cfg);
    let start = Instant::now();
    let res: Result<Arc<ThunderCrabClient>, FfiError> = async {
        let backend =
            tokio::time::timeout(OP_TIMEOUT, RustImapBackend::connect(&account, &password))
                .await
                .map_err(|_| FfiError::Transport {
                    detail: "connect timed out".to_string(),
                })??;
        Ok(Arc::new(ThunderCrabClient {
            inner: Mutex::new(Some(backend)),
        }))
    }
    .await;
    let ms = u64::try_from(start.elapsed().as_millis()).unwrap_or(u64::MAX);
    match &res {
        Ok(_) => telemetry::record_event(DiagKind::ConnectOk, DiagCategory::None, "connect", 0, 0, ms),
        Err(e) => {
            // Distinguish a rejected LOGIN (AuthFail) from a connect/TLS
            // failure so the dashboard separates "wrong password" from
            // "can't reach the server".
            let kind = if matches!(e, FfiError::Auth { .. }) {
                DiagKind::AuthFail
            } else {
                DiagKind::ConnectFail
            };
            telemetry::record_event(kind, ffi_category(e), "connect", 0, 0, ms);
        }
    }
    res
}

#[uniffi::export(async_runtime = "tokio")]
impl ThunderCrabClient {
    /// List all folders the user can see.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if the client was already
    /// logged out.
    pub async fn list_folders(&self) -> Result<Vec<FfiFolder>, FfiError> {
        timed(
            "list_folders",
            DiagKind::ListFoldersOk,
            DiagKind::ListFoldersFail,
            |v: &Vec<FfiFolder>| u64::try_from(v.len()).unwrap_or(u64::MAX),
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                let folders = tokio::time::timeout(OP_TIMEOUT, backend.list_folders())
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "list_folders timed out".to_string(),
                    })??;
                Ok(folders
                    .into_iter()
                    .map(|f| FfiFolder {
                        name: f.name,
                        special_use: f.special_use,
                        messages: f.messages,
                        unseen: f.unseen,
                    })
                    .collect())
            },
        )
        .await
    }

    /// Fetch headers for messages in `folder`, optionally limited to the most
    /// recent `limit`. HEADER-ONLY (`BODY.PEEK[HEADER]`) — no body is read.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn fetch_headers(
        &self,
        folder: String,
        limit: Option<u32>,
    ) -> Result<Vec<FfiHeaders>, FfiError> {
        timed(
            "fetch_headers",
            DiagKind::FetchHeadersOk,
            DiagKind::FetchHeadersFail,
            |v: &Vec<FfiHeaders>| u64::try_from(v.len()).unwrap_or(u64::MAX),
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                let headers =
                    tokio::time::timeout(OP_TIMEOUT, backend.fetch_headers(&folder, limit))
                        .await
                        .map_err(|_| FfiError::Transport {
                            detail: "fetch_headers timed out".to_string(),
                        })??;
                Ok(headers
                    .into_iter()
                    .map(|h| {
                        // Compute before `other_headers` is moved out below.
                        let read_receipt_requested =
                            h.read_receipt_requested().map(String::from);
                        FfiHeaders {
                            uid: h.uid,
                            folder: h.folder,
                            from: h.from,
                            subject: h.subject,
                            other_headers: h
                                .other_headers
                                .into_iter()
                                .map(|(name, value)| FfiHeader { name, value })
                                .collect(),
                            read_receipt_requested,
                        }
                    })
                    .collect())
            },
        )
        .await
    }

    /// Search `folder` for `term`, returning header summaries for the matches
    /// (newest UID first). `term` is a plain string from the UI; the core wraps
    /// it in a safe IMAP `TEXT "<term>"` criterion (server-side full-text over
    /// headers + body), so callers never construct raw IMAP query syntax.
    /// Read-only (`EXAMINE`) — searching never marks anything read.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn search(
        &self,
        folder: String,
        term: String,
    ) -> Result<Vec<FfiHeaders>, FfiError> {
        timed(
            "search",
            DiagKind::FetchHeadersOk,
            DiagKind::FetchHeadersFail,
            |v: &Vec<FfiHeaders>| u64::try_from(v.len()).unwrap_or(u64::MAX),
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                // Build the criterion via the core's single tested helper: it
                // strips control chars (blocks CRLF / IMAP injection) and escapes
                // quoted-specials, so the UI never constructs raw IMAP syntax.
                let query = thundercrab_imap::rust_imap::text_search_criterion(&term);
                let headers = tokio::time::timeout(OP_TIMEOUT, backend.search(&folder, &query))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "search timed out".to_string(),
                    })??;
                Ok(headers
                    .into_iter()
                    .map(|h| {
                        let read_receipt_requested = h.read_receipt_requested().map(String::from);
                        FfiHeaders {
                            uid: h.uid,
                            folder: h.folder,
                            from: h.from,
                            subject: h.subject,
                            other_headers: h
                                .other_headers
                                .into_iter()
                                .map(|(name, value)| FfiHeader { name, value })
                                .collect(),
                            read_receipt_requested,
                        }
                    })
                    .collect())
            },
        )
        .await
    }

    /// Fetch one message's full body, returning display-ready parts: the
    /// plain-text body and the HTML body ALREADY SANITIZED by the core
    /// (scripts + all remote content removed — safe to render in a `WebView`).
    /// Uses `BODY.PEEK`, so previewing does not mark the message read.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn fetch_body(&self, folder: String, uid: u32) -> Result<FfiMessageBody, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        let body = tokio::time::timeout(OP_TIMEOUT, backend.fetch_body(&folder, uid))
            .await
            .map_err(|_| FfiError::Transport {
                detail: "fetch_body timed out".to_string(),
            })??;
        Ok(FfiMessageBody {
            plain: body.plain,
            html_sanitized: body.html_sanitized,
            attachments: body
                .attachments
                .iter()
                .map(|a| FfiAttachment {
                    filename: a.filename.clone(),
                    mime_type: a.mime_type.clone(),
                    size: a.size() as u64,
                })
                .collect(),
        })
    }

    /// Fetch the decoded bytes of one attachment by its index in the message's
    /// `attachments` list (from [`Self::fetch_body`]). Kept separate from
    /// `fetch_body` so listing a message stays cheap regardless of attachment
    /// size. Uses `BODY.PEEK`, so it does not mark the message read.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `InvalidInput` if `index` is out of range;
    /// `NotImplemented` if already logged out.
    pub async fn fetch_attachment(
        &self,
        folder: String,
        uid: u32,
        index: u32,
    ) -> Result<Vec<u8>, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        let body = tokio::time::timeout(OP_TIMEOUT, backend.fetch_body(&folder, uid))
            .await
            .map_err(|_| FfiError::Transport {
                detail: "fetch_attachment timed out".to_string(),
            })??;
        let idx = index as usize;
        body.attachments
            .get(idx)
            .map(|a| a.bytes.clone())
            .ok_or_else(|| FfiError::InvalidInput {
                detail: format!(
                    "no attachment at index {idx}; message has {}",
                    body.attachments.len()
                ),
            })
    }

    /// Build a plain-text diagnostics report and append it to the
    /// `ThunderCrab-Diagnostics` folder of the user's OWN mailbox (IMAP
    /// `APPEND`; the folder is created if missing). Sovereign by construction:
    /// the report never touches a third party — it lands where the user's mail
    /// already lives, readable by whoever administers their own server.
    ///
    /// `context` is app-supplied free text (app version, device model, OS
    /// level, and optionally what the user was doing). The report carries the
    /// PII-free diagnostic events PLUS the on-device error/breadcrumb ring.
    /// Explicitly user-initiated — never called automatically.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn send_diagnostics_report(&self, context: String) -> Result<(), FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;

        let now = chrono::Utc::now();
        let mut body = String::new();
        body.push_str(&format!(
            "ThunderCrab diagnostic report\ngenerated_at: {}\nffi_version: {}\n\n== context ==\n{}\n",
            now.to_rfc3339(),
            env!("CARGO_PKG_VERSION"),
            context,
        ));
        body.push_str("\n== client events + errors (oldest first, on-device ring) ==\n");
        {
            let ring = ERROR_RING.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            if ring.is_empty() {
                body.push_str("(none recorded)\n");
            }
            for (at, op, detail) in ring.iter() {
                body.push_str(&format!("{at} [{op}] {detail}\n"));
            }
        }
        body.push_str("\n== diagnostic events (PII-free ring) ==\n");
        for e in telemetry::snapshot() {
            let e = FfiDiagEvent::from(e);
            body.push_str(&format!(
                "{} {} cat={} op={} count={} extra={} ms={}\n",
                e.at_unix_ms, e.kind, e.category, e.op, e.count, e.extra, e.duration_ms,
            ));
        }

        // Minimal RFC 5322 wrapper; CRLF line endings for IMAP APPEND.
        let message = format!(
            "Subject: ThunderCrab diagnostic report {}\r\nDate: {}\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n{}",
            now.format("%Y-%m-%dT%H:%M:%SZ"),
            now.to_rfc2822(),
            body.replace('\n', "\r\n"),
        );

        tokio::time::timeout(
            OP_TIMEOUT,
            backend.append_message("ThunderCrab-Diagnostics", message.as_bytes()),
        )
        .await
        .map_err(|_| FfiError::Transport {
            detail: "send_diagnostics_report timed out".to_string(),
        })??;
        Ok(())
    }

    /// Fetch the synced personalization blob (RFC 5464 IMAP METADATA on the
    /// user's own mailbox — no third-party sync server). `null` if nothing is
    /// stored or the server has no METADATA support.
    ///
    /// # Errors
    /// `Protocol` on a malformed server response; `NotImplemented` if logged out.
    pub async fn get_personalization(&self) -> Result<Option<String>, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        Ok(tokio::time::timeout(OP_TIMEOUT, backend.get_personalization())
            .await
            .map_err(|_| FfiError::Transport {
                detail: "get_personalization timed out".to_string(),
            })??)
    }

    /// Store the personalization blob (`json`) as IMAP METADATA so it syncs to
    /// every device on the next fetch. Opaque to the FFI — the client owns the
    /// schema (rules, layout, appearance, …).
    ///
    /// # Errors
    /// `Protocol` if `SETMETADATA` is rejected; `NotImplemented` if logged out.
    pub async fn set_personalization(&self, json: String) -> Result<(), FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        tokio::time::timeout(OP_TIMEOUT, backend.set_personalization(&json))
            .await
            .map_err(|_| FfiError::Transport {
                detail: "set_personalization timed out".to_string(),
            })??;
        Ok(())
    }

    /// Fetch a named synced blob (`key`: `personalization`, `rules`, …) from the
    /// user's own mailbox via IMAP METADATA. Several independently-owned blobs
    /// can sync without clobbering each other. `null` if unset / no METADATA.
    ///
    /// # Errors
    /// `Protocol` on a malformed server response; `NotImplemented` if logged out.
    pub async fn get_synced(&self, key: String) -> Result<Option<String>, FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        Ok(tokio::time::timeout(OP_TIMEOUT, backend.get_synced(&key))
            .await
            .map_err(|_| FfiError::Transport {
                detail: "get_synced timed out".to_string(),
            })??)
    }

    /// Store a named synced blob (`json`) under `key` as IMAP METADATA.
    ///
    /// # Errors
    /// `Protocol` if `SETMETADATA` is rejected; `NotImplemented` if logged out.
    pub async fn set_synced(&self, key: String, json: String) -> Result<(), FfiError> {
        let guard = self.inner.lock().await;
        let backend = guard.as_ref().ok_or_else(client_gone)?;
        tokio::time::timeout(OP_TIMEOUT, backend.set_synced(&key, &json))
            .await
            .map_err(|_| FfiError::Transport {
                detail: "set_synced timed out".to_string(),
            })??;
        Ok(())
    }

    /// Move `uid` from `from_folder` to `to_folder` (the IMAP side of a
    /// recorded flag-event move).
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn move_message(
        &self,
        from_folder: String,
        to_folder: String,
        uid: u32,
    ) -> Result<(), FfiError> {
        timed(
            "move_message",
            DiagKind::MoveOk,
            DiagKind::MoveFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(
                    OP_TIMEOUT,
                    backend.move_message(&from_folder, &to_folder, uid),
                )
                .await
                .map_err(|_| FfiError::Transport {
                    detail: "move_message timed out".to_string(),
                })??;
                Ok(())
            },
        )
        .await
    }

    /// Set or clear an IMAP `flag` on `uid` in `folder` (the IMAP side of a
    /// recorded flag-event toggle).
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn set_flag(
        &self,
        folder: String,
        uid: u32,
        flag: String,
        set: bool,
    ) -> Result<(), FfiError> {
        timed(
            "set_flag",
            DiagKind::FlagOk,
            DiagKind::FlagFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(OP_TIMEOUT, backend.set_flag(&folder, uid, &flag, set))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "set_flag timed out".to_string(),
                    })??;
                Ok(())
            },
        )
        .await
    }

    /// Create a new mailbox (graphical "add folder"). `name` is the full
    /// server path with the server's hierarchy separator.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn create_folder(&self, name: String) -> Result<(), FfiError> {
        timed(
            "create_folder",
            DiagKind::FolderMutateOk,
            DiagKind::FolderMutateFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(OP_TIMEOUT, backend.create_folder(&name))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "create_folder timed out".to_string(),
                    })??;
                Ok(())
            },
        )
        .await
    }

    /// Rename / move a mailbox.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn rename_folder(&self, from: String, to: String) -> Result<(), FfiError> {
        timed(
            "rename_folder",
            DiagKind::FolderMutateOk,
            DiagKind::FolderMutateFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(OP_TIMEOUT, backend.rename_folder(&from, &to))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "rename_folder timed out".to_string(),
                    })??;
                Ok(())
            },
        )
        .await
    }

    /// Delete a mailbox. The UI is responsible for confirming first.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn delete_folder(&self, name: String) -> Result<(), FfiError> {
        timed(
            "delete_folder",
            DiagKind::FolderMutateOk,
            DiagKind::FolderMutateFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(OP_TIMEOUT, backend.delete_folder(&name))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "delete_folder timed out".to_string(),
                    })??;
                Ok(())
            },
        )
        .await
    }

    /// Subscribe (`true`) or unsubscribe (`false`) a mailbox.
    ///
    /// # Errors
    /// `Protocol` on IMAP failure; `NotImplemented` if already logged out.
    pub async fn set_subscribed(&self, name: String, subscribed: bool) -> Result<(), FfiError> {
        timed(
            "set_subscribed",
            DiagKind::FolderMutateOk,
            DiagKind::FolderMutateFail,
            |_: &()| 0,
            async {
                let guard = self.inner.lock().await;
                let backend = guard.as_ref().ok_or_else(client_gone)?;
                tokio::time::timeout(OP_TIMEOUT, backend.set_subscribed(&name, subscribed))
                    .await
                    .map_err(|_| FfiError::Transport {
                        detail: "set_subscribed timed out".to_string(),
                    })??;
                Ok(())
            },
        )
        .await
    }

    /// Log out cleanly. Consumes the inner backend via `.take()`; subsequent
    /// calls on this client return `NotImplemented`. Best-effort — a failed
    /// logout drops the session anyway.
    pub async fn logout(&self) {
        let backend = {
            let mut guard = self.inner.lock().await;
            guard.take()
        };
        if let Some(backend) = backend {
            // Best-effort + bounded: a stalled server must not hang disconnect.
            let _ = tokio::time::timeout(OP_TIMEOUT, backend.logout()).await;
        }
    }
}

/// `NotImplemented` produced when an operation is attempted on a client whose
/// backend was already taken by `logout`.
fn client_gone() -> FfiError {
    FfiError::NotImplemented {
        detail: "client has been logged out".to_string(),
    }
}

// =============================================================================
// IMAP IDLE push watcher
// =============================================================================

/// The outcome of one [`ThunderCrabIdleWatcher::wait`]. Flat mirror of
/// [`thundercrab_imap::idle::IdleEvent`] for the binding.
#[derive(uniffi::Enum, Clone, Copy, Debug, PartialEq, Eq)]
pub enum FfiIdleEvent {
    /// The server reported activity on the watched folder. The caller should
    /// re-fetch headers (e.g. via a separate [`ThunderCrabClient`]) and post a
    /// notification, then resume watching.
    Activity,
    /// The re-arm timeout elapsed with no activity — just resume watching.
    Idle,
}

impl From<idle::IdleEvent> for FfiIdleEvent {
    fn from(e: idle::IdleEvent) -> Self {
        match e {
            idle::IdleEvent::Activity => Self::Activity,
            idle::IdleEvent::Idle => Self::Idle,
        }
    }
}

/// A dedicated IMAP IDLE connection for push-style mail arrival, intended to
/// be held for the lifetime of an Android foreground service that holds a
/// Keystore-encrypted password for reconnects.
///
/// A *separate* object from [`ThunderCrabClient`] by design: IMAP is
/// single-channel, so a connection parked in IDLE cannot also serve the UI's
/// LIST / FETCH. The inner [`IdleWatcher`] is held as `Mutex<Option<…>>`
/// because each [`IdleWatcher::wait`] consumes and returns it; `take` +
/// replace threads the owned watcher through the object's `&self` surface.
///
/// ## Lifecycle
/// Drive [`ThunderCrabIdleWatcher::wait`] (or [`Self::wait_rearm`]) in a loop
/// from one service coroutine. A failed wait leaves the slot empty, so the
/// next call returns `NotImplemented` and the service should reconnect via
/// [`connect_idle`]. To stop watching, drop the object (which closes the IMAP
/// connection) or call [`Self::logout`] between waits — `wait` holds the
/// connection for its whole duration, so it cannot be interrupted mid-park.
#[derive(uniffi::Object)]
pub struct ThunderCrabIdleWatcher {
    inner: Mutex<Option<IdleWatcher>>,
}

/// Connect, authenticate, and `SELECT` `folder` (e.g. `"INBOX"`), leaving a
/// watcher parked and ready to IDLE. Free async fn (returns `Result`,
/// mirroring [`connect`]); the connect itself is bounded by `OP_TIMEOUT`,
/// but the subsequent [`ThunderCrabIdleWatcher::wait`] is intentionally not.
///
/// The password is used only for `LOGIN` and is not retained.
///
/// # Errors
/// `Transport` if TCP/TLS/greeting fails or the connect times out; `Auth` if
/// `LOGIN` is rejected; `Protocol` if `SELECT folder` fails.
#[uniffi::export(async_runtime = "tokio")]
pub async fn connect_idle(
    cfg: FfiAccountConfig,
    password: String,
    folder: String,
) -> Result<Arc<ThunderCrabIdleWatcher>, FfiError> {
    let account = AccountConfig::from(&cfg);
    let watcher = tokio::time::timeout(
        OP_TIMEOUT,
        IdleWatcher::connect(&account, &password, &folder),
    )
    .await
    .map_err(|_| FfiError::Transport {
        detail: "connect_idle timed out".to_string(),
    })??;
    Ok(Arc::new(ThunderCrabIdleWatcher {
        inner: Mutex::new(Some(watcher)),
    }))
}

#[uniffi::export(async_runtime = "tokio")]
impl ThunderCrabIdleWatcher {
    /// Park in IDLE until the server reports activity or `timeout_secs`
    /// elapses, whichever comes first; return which happened. Prefer
    /// [`Self::wait_rearm`] for the RFC-2177-safe interval.
    ///
    /// Holds the connection for the whole call. On success the watcher is
    /// retained for the next call; on error it is dropped (the connection is
    /// spent) and subsequent calls return `NotImplemented`.
    ///
    /// # Errors
    /// `Protocol` if the IDLE/DONE handshake fails (typically a dropped
    /// connection — reconnect via [`connect_idle`]); `NotImplemented` if the
    /// watcher was already logged out or spent.
    pub async fn wait(&self, timeout_secs: u64) -> Result<FfiIdleEvent, FfiError> {
        let mut guard = self.inner.lock().await;
        let watcher = guard.take().ok_or_else(client_gone)?;
        // On error the watcher has been moved into `wait` and dropped, so the
        // slot stays `None` — exactly the "spent connection" signal we want.
        let (event, watcher) = watcher
            .wait(std::time::Duration::from_secs(timeout_secs))
            .await?;
        *guard = Some(watcher);
        Ok(event.into())
    }

    /// [`Self::wait`] using the RFC-2177-safe re-arm interval
    /// ([`thundercrab_imap::idle::IDLE_REARM`], 29 minutes).
    ///
    /// # Errors
    /// As [`Self::wait`].
    pub async fn wait_rearm(&self) -> Result<FfiIdleEvent, FfiError> {
        self.wait(idle::IDLE_REARM.as_secs()).await
    }

    /// Log out cleanly, leaving the watcher inert. Best-effort + bounded — a
    /// stalled server must not hang shutdown. Only takes effect between waits
    /// (a wait in progress holds the lock until it returns).
    pub async fn logout(&self) {
        let watcher = {
            let mut guard = self.inner.lock().await;
            guard.take()
        };
        if let Some(watcher) = watcher {
            let _ = tokio::time::timeout(OP_TIMEOUT, watcher.logout()).await;
        }
    }
}

// =============================================================================
// Tests — logic-free seams only (no live IMAP / SMTP / ManageSieve).
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_is_nonempty() {
        assert!(!thundercrab_version().is_empty());
    }

    #[test]
    fn plausiden_config_delegates_to_core() {
        let c = plausiden_account_config("kadyn@plausiden.com".into());
        // Must match AccountConfig::plausiden exactly — no re-hardcoding here.
        let expected = AccountConfig::plausiden("mail.plausiden.com", "kadyn@plausiden.com");
        assert_eq!(c.imap_host, expected.imap_host);
        assert_eq!(c.imap_port, expected.imap_port);
        assert_eq!(c.smtp_host, expected.smtp_host);
        assert_eq!(c.smtp_port, expected.smtp_port);
        assert_eq!(c.sieve_port, expected.sieve_port);
        assert_eq!(c.username, "kadyn@plausiden.com");
    }

    #[test]
    fn account_config_round_trips_through_core() {
        let original = plausiden_account_config("x@plausiden.com".into());
        let core = AccountConfig::from(&original);
        let back = FfiAccountConfig::from(core);
        assert_eq!(back.imap_host, original.imap_host);
        assert_eq!(back.sieve_port, original.sieve_port);
        assert_eq!(back.username, original.username);
    }

    #[test]
    fn backend_error_maps_to_fielded_variants() {
        assert!(matches!(
            FfiError::from(BackendError::Transport("x".into())),
            FfiError::Transport { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::Auth("x".into())),
            FfiError::Auth { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::Protocol("x".into())),
            FfiError::Protocol { .. }
        ));
        assert!(matches!(
            FfiError::from(BackendError::NotImplemented("x")),
            FfiError::NotImplemented { .. }
        ));
    }

    #[test]
    fn crab_rule_json_round_trips_with_snake_case_tags() {
        let ffi = FfiCrabRule {
            id: "promotions".into(),
            display_name: "Promotions".into(),
            when_json: r#"{"kind":"has_header","header":"List-Unsubscribe"}"#.into(),
            action_json: r#"{"kind":"file_into","folder":"Promotions"}"#.into(),
            score: 80,
            stop_on_match: true,
            origin: FfiRuleOrigin::Platform,
        };
        let core = CrabRule::try_from(&ffi).expect("valid AST parses");
        assert_eq!(core.score, 80);
        // Round-trip back out and confirm the canonical snake_case tags
        // survive (this is the mail_config wire-compat guarantee).
        let back = FfiCrabRule::try_from(&core).expect("re-serializes");
        assert!(back.when_json.contains("\"kind\":\"has_header\""));
        assert!(back.action_json.contains("\"kind\":\"file_into\""));
    }

    #[test]
    fn crab_rule_rejects_malformed_ast() {
        let ffi = FfiCrabRule {
            id: "bad".into(),
            display_name: "Bad".into(),
            when_json: "not json".into(),
            action_json: r#"{"kind":"file_into","folder":"X"}"#.into(),
            score: 1,
            stop_on_match: false,
            origin: FfiRuleOrigin::User,
        };
        assert!(matches!(
            CrabRule::try_from(&ffi),
            Err(FfiError::InvalidInput { .. })
        ));
    }

    #[test]
    fn flag_event_rejects_wrong_length_hash() {
        let ev = FfiFlagEvent {
            message_hash: vec![0u8; 16], // wrong length
            source: FfiFlagSource::ManualMove,
            destination: "Promotions".into(),
            from_domain_with_at: "@x.com".into(),
            list_id: None,
            has_list_unsubscribe: false,
            subject_tokens: vec![],
            priority_high: false,
            observed_at: 0,
        };
        assert!(matches!(
            FlagEvent::try_from(&ev),
            Err(FfiError::InvalidInput { .. })
        ));
    }

    #[test]
    fn flag_event_accepts_valid_hash_and_timestamp() {
        let ev = FfiFlagEvent {
            message_hash: vec![7u8; 32],
            source: FfiFlagSource::ExplicitCategory,
            destination: "Promotions".into(),
            from_domain_with_at: "@mailchimp.com".into(),
            list_id: Some("news.mailchimp.com".into()),
            has_list_unsubscribe: true,
            subject_tokens: vec!["sale".into()],
            priority_high: false,
            observed_at: 1_700_000_000,
        };
        let core = FlagEvent::try_from(&ev).expect("valid event converts");
        assert_eq!(core.message_hash, [7u8; 32]);
        assert_eq!(core.observed_at.timestamp(), 1_700_000_000);
    }

    #[test]
    fn store_record_and_load_round_trip() {
        // Use a temp file DB (Db::open needs a path; :memory: is per-conn and
        // with_db opens a fresh conn each call, so an in-memory DB wouldn't
        // persist across the record/load calls).
        let dir = std::env::temp_dir();
        let path = dir.join(format!("tc_ffi_test_{}.db", std::process::id()));
        let path_str = path.to_string_lossy().to_string();
        let _ = std::fs::remove_file(&path);

        let rule = FfiCrabRule {
            id: "x".into(),
            display_name: "X".into(),
            when_json: r#"{"kind":"always"}"#.into(),
            action_json: r#"{"kind":"file_into","folder":"Forums"}"#.into(),
            score: 75,
            stop_on_match: true,
            origin: FfiRuleOrigin::User,
        };
        save_rule(path_str.clone(), rule).expect("save");
        let loaded = load_rules(path_str.clone()).expect("load");
        assert_eq!(loaded.len(), 1);
        assert_eq!(loaded[0].id, "x");
        assert!(delete_rule(path_str.clone(), "x".into()).expect("delete"));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn preview_suggestions_returns_safe_candidates() {
        let dir = std::env::temp_dir();
        let path = dir.join(format!("tc_ffi_sugg_{}.db", std::process::id()));
        let path_str = path.to_string_lossy().to_string();
        let _ = std::fs::remove_file(&path);

        // Record a clear signal: @clear.com → Promotions, 4 distinct events.
        for h in 0..4u8 {
            let ev = FfiFlagEvent {
                message_hash: vec![h; 32],
                source: FfiFlagSource::ManualMove,
                destination: "Promotions".into(),
                from_domain_with_at: "@clear.com".into(),
                list_id: None,
                has_list_unsubscribe: false,
                subject_tokens: vec![],
                priority_high: false,
                observed_at: 1_700_000_000,
            };
            record_flag_event(path_str.clone(), ev).expect("record");
        }
        let suggestions = preview_suggestions(path_str.clone(), 3, 0.7).expect("preview");
        assert_eq!(suggestions.len(), 1);
        // Safety gate re-marks origin=Federated.
        assert!(matches!(suggestions[0].origin, FfiRuleOrigin::Federated));
        assert!(suggestions[0].when_json.contains("@clear.com"));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn preview_suggestions_skips_unsafe_candidates_without_erroring() {
        // Regression: a derived candidate that fails the safety gate (e.g.
        // file-into-INBOX, a protected folder) must be SKIPPED — not error the
        // whole preview. Before the fix, apply_suggestion(..)? aborted the batch.
        let path = std::env::temp_dir().join(format!("tc_ffi_sugg_skip_{}.db", std::process::id()));
        let path_str = path.to_string_lossy().to_string();
        let _ = std::fs::remove_file(&path);

        // Safe signal: @clear.com → Promotions (passes the gate).
        for h in 0..4u8 {
            record_flag_event(path_str.clone(), FfiFlagEvent {
                message_hash: vec![h; 32], source: FfiFlagSource::ManualMove,
                destination: "Promotions".into(), from_domain_with_at: "@clear.com".into(),
                list_id: None, has_list_unsubscribe: false, subject_tokens: vec![],
                priority_high: false, observed_at: 1_700_000_000,
            }).expect("record safe");
        }
        // Unsafe signal: @spam.com → INBOX (protected folder; gate rejects it).
        for h in 10..14u8 {
            record_flag_event(path_str.clone(), FfiFlagEvent {
                message_hash: vec![h; 32], source: FfiFlagSource::ManualMove,
                destination: "INBOX".into(), from_domain_with_at: "@spam.com".into(),
                list_id: None, has_list_unsubscribe: false, subject_tokens: vec![],
                priority_high: false, observed_at: 1_700_000_000,
            }).expect("record unsafe");
        }

        // Must NOT error, and returns only the gate-passing candidate.
        let suggestions = preview_suggestions(path_str.clone(), 3, 0.7)
            .expect("preview must not error on an unsafe candidate");
        assert_eq!(suggestions.len(), 1, "only the gate-passing candidate should survive");
        assert!(suggestions[0].when_json.contains("@clear.com"));
        assert!(suggestions.iter().all(|s| !s.action_json.contains("INBOX")));

        let _ = std::fs::remove_file(&path);
    }
}
